/* Three sectors per chapter. Paths omit content; a checkpoint preserves the route. */
(function(root){'use strict';const C=root.BFContent,G=root.BlackForest.Game,P=G.prototype;
C.TYPES.story=['서사의 흔적','지역의 기억과 세력의 선택'];C.TYPES.npc=['낯익은 목소리','개인 관계에 따른 대화'];C.TYPES.checkpoint=['중간 야영지','회복 · 경로를 보존하고 캠프로'];C.TYPES.midboss=['중간 수문장','정예 보상 · 지역 인장은 유지'];
C.CHAPTERS=[
 {npc:'alice',midboss:false,text:['토끼굴의 문짝이 나무뿌리에 걸려 있다. 앨리스의 증언 한 장이 바람에 날린다. 법정은 이 길을 존재하지 않는 길이라 부른다.','뿌리에 묶인 기억은 거짓 증언이 아니라 돌아갈 집을 잃은 사람의 이름이었다. 누가 이 이름을 지울 권리가 있는가?','파수꾼의 가시는 숲 밖의 명령으로 자랐다. 이름을 보존할지, 질서를 위해 봉인할지, 그 명령을 추적할지 정해야 한다.']},
 {npc:'creature',midboss:false,text:['멈춘 종탑 아래에서 피조물이 망가진 등불을 고친다. 주민은 그의 손을 두려워하지만 밤이 오면 그 불빛을 찾는다.','빅터의 기록에는 주민이 재료 목록으로 남아 있다. 피조물은 목록 한 줄을 자기 이름으로 바꾸겠다고 한다.','종지기의 종은 마을을 살리는 장치인 동시에 기억을 지우는 장치다. 심장을 살릴 다른 힘을 모아야 한다.']},
 {npc:'ahab',midboss:true,text:['바다를 잃은 백경의 그림자가 유리 수면을 지난다. 에이해브의 작살은 물 아래보다 당신의 결심을 겨눈다.','거울은 살아남은 사람에게 사냥의 결말을 보여 준다. 백경을 죽인 뒤에도 사냥꾼의 빈자리는 채워지지 않는다.','거울의 마녀가 백경의 상처를 증거로 내민다. 상처를 구할 것인가, 봉인할 것인가, 상처를 만든 사슬을 쫓을 것인가?']},
 {npc:'queen',midboss:false,text:['왕성의 문은 모든 손님에게 죄목을 붙인다. 여왕의 도장은 질서를 약속하며 지나간 선택까지 고쳐 쓴다.','여왕은 끝없는 예외가 세계를 찢는다고 믿는다. 앨리스의 목소리를 법 안에 남길 방법을 묻는다.','집행관은 내려진 판결만 읽을 뿐 증언을 듣지 않는다. 당신이 모은 목소리를 왕성의 중심에 돌려주어야 한다.']},
 {npc:'quixote',midboss:false,text:['모래를 건너는 배 옆에서 돈키호테가 풍차 그림자에 방패를 든다. 에이해브는 그것이 백경의 길이라고 말한다.','산초는 물통을 나누며 꿈이 사람을 먹여 살릴 수 있느냐고 묻는다. 꿈을 버리지 않고도 오늘을 버틸 길을 찾는다.','예언자는 이미 쓰인 마지막 항해를 내민다. 돌아올 사람의 이름을 먼저 적으면 다른 결말도 가능한가?']},
 {npc:'alice',midboss:true,text:['달빛이 비추는 서가에 앨리스의 증언과 빅터의 실험 기록이 나란히 놓여 있다. 두 책은 서로를 오류라 부른다.','사서는 이름을 한 문장으로 고정하면 죽음을 막을 수 있다고 말한다. 고정된 사람은 새로운 선택을 할 수 없다.','마지막 서가에는 아직 쓰지 않은 여백이 남았다. 법정의 질서와 사람의 자유를 함께 기록할 방법을 골라야 한다.']},
 {npc:'victor',midboss:false,text:['식지 않는 용광로 앞에서 빅터는 실패한 창조물의 이름을 센다. 거인은 이름보다 명령에 먼저 반응한다.','피조물의 심장과 사람들의 불씨를 잇는 회로가 드러난다. 생명을 재료로 쓰지 않으려면 책임을 나누어야 한다.','봉합 거인에게는 창조주의 명령과 스스로 살고 싶은 마음이 충돌한다. 심장을 멈추기 전에 그의 목소리를 들어야 한다.']},
 {npc:'creature',midboss:false,text:['새벽 없는 왕좌로 가는 길에 되찾은 이름들이 모인다. 당신의 동료는 어떤 선택이 자신들을 여기로 데려왔는지 기억한다.','편집자는 모든 이야기를 하나의 결말로 정리하겠다고 말한다. 지워질 이름을 지킬 힘은 장비보다 지난 선택에서 나온다.','첫 불씨 안에서 왕관과 여백이 함께 빛난다. 구한 사람들, 따랐던 법, 끝까지 쫓은 사냥이 마지막 문장을 기다린다.']}
];
for(const ch of C.CHAPTERS)ch.candidates=['outer-story','outer-battle','outer-event','outer-cache','depth-battle','depth-elite','depth-npc','depth-secret','depth-merchant','depth-mystery','core-story','core-elite',ch.midboss?'core-midboss':'core-battle','core-shrine','core-checkpoint','core-boss'];
P.sector=function(){return this.s.step<4?'외곽':this.s.step<8?'심부':'중심부';};P.limit=function(){return this.s.kind==='rift'?4:12;};
const travel=P.travel;P.travel=function(a){if(this.s.scene!=='camp'||this.s.checkpoint)return;travel.call(this,a);if(this.s.scene==='map'&&this.s.kind==='story'){this.s.storyFlags['chapter_'+this.s.area+'_entered']=true;this.note(C.AREAS[this.s.area].subtitle+'\n앞에 무엇이 기다리는지는 알 수 없다.');}};
const oldroutes=P.routes;P.routes=function(){if(this.s.kind==='rift')return oldroutes.call(this);const s=this.s;if(s.step>=12){s.routes=['boss'];return;}const pools=[{battle:35,event:22,cache:20,shrine:8,merchant:7,mystery:8},{battle:24,elite:18,event:18,cache:10,npc:10,secret:9,mystery:11},{battle:20,elite:22,event:12,shrine:16,secret:9,merchant:7,mystery:14}];const pool=pools[Math.min(2,Math.floor(s.step/4))];let type=null;
 if([0,4,8].includes(s.step))type='story';else if(s.step===5)type='npc';else if(s.step===3||s.step===7||s.step===11)type='checkpoint';else if(s.step===10&&C.CHAPTERS[s.area].midboss&&!s.midbosses.includes(s.area))type='midboss';else if(s.secretPity>=11)type='secret';else type=this.weighted(Object.entries(pool));s.routes=[type];};
const choose=P.choose;P.choose=function(i){const s=this.s;if(s.scene!=='map'||!s.routes[i])return;const type=s.routes[i];if(!['story','npc','checkpoint','midboss'].includes(type))return choose.call(this,i);const sector=Math.min(2,Math.floor(s.step/4));s.turns++;s.step++;s.secretPity++;if(type==='story'){s.scene='chapter';s.chapterSector=sector;this.note(C.CHAPTERS[s.area].text[sector]);return;}if(type==='npc'){const id=C.CHAPTERS[s.area].npc;s.storyFlags[id+'_seen']=true;if(s.npcVisits[id]===s.cleared.length){s.scene='reward';this.note(C.NPCS[id].name+'는 지난 대화를 기억한다. “다음 인장을 되찾으면 다시 이야기하자.”');}else{s.thread=id;s.npcReturn='reward';s.scene='npc';this.note(C.NPCS[id].text+'\n관계: '+this.affinityTier(id));}return;}if(type==='checkpoint'){s.hp=this.maxHp();s.mp=this.maxMp();s.scene='reward';this.note('중간 야영지. HP·MP를 회복했다. 진행을 보존하고 캠프에서 정비하거나 탐험을 계속할 수 있다.');return;}if(type==='midboss'){this.fight(true);s.enemy.midboss=true;s.enemy.name=C.AREAS[s.area].name+'의 수문장';s.enemy.hp=s.enemy.maxHp=Math.round(s.enemy.maxHp*.7);this.note(s.enemy.name+'가 중심부로 가는 길을 막는다.');}};
P.chapterChoice=function(i){const s=this.s;if(s.scene!=='chapter'||![0,1,2].includes(i))return;const record='chapter_'+s.area+'_'+s.chapterSector;if(s.decisions[record]){s.scene='reward';this.note('이미 남긴 선택: '+s.decisions[record]+'. 같은 사건의 보상은 다시 받지 않는다.');return;}const id=C.CHAPTERS[s.area].npc,faction=['lantern','ink','hunt'][i];s.factions[faction]=Math.min(100,s.factions[faction]+1);this.addAffinity(id,i===0?5:i===1?-2:2);s.storyFlags['chapter_'+s.area+'_seen']=true;s.storyFlags[id+'_seen']=true;s.decisions['chapter_'+s.area+'_'+s.chapterSector]=['이름을 보존','기록을 봉인','근원을 추적'][i];s.scene='reward';this.note(C.CHAPTERS[s.area].text[s.chapterSector]+'\n'+s.decisions['chapter_'+s.area+'_'+s.chapterSector]+'. '+C.NPCS[id].name+' 호감도 '+(i===0?'+5':i===1?'−2':'+2')+' · '+C.FACTIONS.find(x=>x.id===faction).name+' 평판 +1.');};
P.pauseChapter=function(){const s=this.s;if(s.kind!=='story'||!['reward','map'].includes(s.scene)||![4,8,12].includes(s.step))return;if(s.scene==='reward')this.routes();s.checkpoint={area:s.area,step:s.step,routes:[...s.routes]};s.scene='camp';this.note('야영 지점에서 탐험을 보존했다. 정비 후 같은 지점에서 이어갈 수 있다.');};
P.resumeChapter=function(){const s=this.s,c=s.checkpoint;if(s.scene!=='camp'||!c)return;s.area=c.area;s.step=c.step;s.kind='story';s.checkpoint=null;s.scene='map';s.routes=[...c.routes];this.note(C.AREAS[s.area].name+' · '+this.sector()+' 탐험을 이어 간다.');};
P.abandonChapter=function(){if(this.s.scene!=='camp'||!this.s.checkpoint)return;this.s.checkpoint=null;this.s.step=0;this.s.routes=[];this.note('보존한 진행을 포기했다. 다음 탐험은 입구에서 시작한다.');};
const npc=P.npcChoice;P.npcChoice=function(i){const back=this.s.npcReturn||'camp';npc.call(this,i);if(this.s.scene==='camp'){this.s.storyFlags[this.s.thread+'_seen']=true;this.s.scene=back;this.s.npcReturn='camp';}};
const meet=P.meetNpc;P.meetNpc=function(id){meet.call(this,id);if(this.s.scene==='npc'){this.s.storyFlags[id+'_seen']=true;this.s.npcReturn='camp';}};
const thread=P.thread;P.thread=function(id){thread.call(this,id);if(this.s.scene==='dialogue')this.s.storyFlags[(id==='adam'?'creature':id)+'_seen']=true;};
root.BlackForest.CHAPTERS=C.CHAPTERS;
})(globalThis);
