const fs=require('node:fs'),assert=require('node:assert/strict'),pw=require('playwright'),{Game,P2_EVENTS,ASSETS}=require('./test-support.cjs'),{entries}=require('./p2-browser-fixtures.cjs');
const fixtures=entries(),engine=process.env.BF_BROWSER||'chromium',base=process.env.BF_QA_URL||'http://127.0.0.1:4181/',key='black-forest-last-ember-v2',out=process.env.BF_P2_OUT||'docs/p2';
(async()=>{const browser=await pw[engine].launch(require('./qa-browser.cjs')()),checks=[];try{for(const width of [360,390,430]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const tap=async l=>{await page.waitForTimeout(280);await l.scrollIntoViewIfNeeded();await l.tap();};
 const current=async()=>Game.load(await page.evaluate(k=>localStorage.getItem(k),key));
 const restore=async code=>{await tap(page.locator('[data-ui="save"]').first());await page.locator('#bf-code').fill(code);await tap(page.locator('[data-ui="load"]'));assert(await page.locator('#bf-panel').isHidden());assert.equal((await current()).export(),code);};
 async function inspect(label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' overflow');for(const l of await page.locator('#bf-play .actions button').all()){const box=await l.boundingBox();assert(box.width>=40&&box.height>=44,label+' touch bounds');assert(await l.evaluate(e=>e.scrollWidth<=e.clientWidth+2),label+' clipped button');}
  assert.equal(await page.locator('.scene-hero-body').evaluateAll(es=>es.filter(e=>e.scrollHeight>e.clientHeight+2).length),0,label+' clipped narration');for(const img of await page.locator('#bf-play img:visible').all())await img.evaluate(e=>e.decode());assert.deepEqual(errors,[]);}
 async function command(g,name,arg){const expected=Game.load(g.export());expected[name](arg);assert.notEqual(expected.export(),g.export(),name+' must progress');await tap(page.locator(`[data-cmd="${name}"]`+(arg!==undefined?`[data-arg="${arg}"]`:'')).first());assert.equal((await current()).export(),expected.export(),name+' UI matches engine');return expected;}
 await page.goto(base);await tap(page.locator('[data-cmd="start"][data-arg="warrior"]'));let started=await current();started=await command(started,'enterArea',0);started=await command(started,'chapterChoice',0);await inspect('real new game');
 for(const ev of P2_EVENTS)for(let choice=0;choice<3;choice++){
  await restore(fixtures[ev.region].code);let g=await current();g=await command(g,'choose',0);assert.equal(g.s.eventId,ev.id);assert.equal(await page.locator('[data-cmd="event"]').count(),3);if(ev.id===20)assert((await page.locator('[data-cmd="event"][data-arg="0"]').textContent()).includes('MP 4'),'MP cost label');assert.equal(await page.locator('.scene-hero img').getAttribute('src'),ASSETS.areas[ev.region]);await inspect('regional '+ev.id);if(choice===0){fs.mkdirSync('screenshots/p2',{recursive:true});await page.screenshot({path:`screenshots/p2/${engine}-${width}-${ev.id}-entry.png`,fullPage:true});}
  const options=g.eventChoices();assert(g.canPay(options[choice].cost),'actual campaign entry can pay choice');g=await command(g,'event',choice);const recorded=g.s.decisions[ev.key];assert(recorded);await inspect('choice '+ev.id+':'+choice);const code=g.export();await page.reload();assert.equal((await current()).export(),code,'choice persists after reconnection');
  let battle=false,gear=false,reaction=false,steps=0;
  while(!(battle&&gear&&reaction)&&steps++<150){const s=g.s;
   if(s.scene==='battle'){battle=true;g=await command(g,'act',s.hp<g.maxHp()&&s.hp<Math.max(g.damagePreview()+8,g.maxHp()*.27)&&s.potions?'potion':s.enemy.intent==='heavy'&&g.damagePreview()>0?'defend':s.mp>=g.skillCost()?'skill':'attack');}
   else if(s.scene==='loot'){gear=true;assert((await page.locator('#bf-play').textContent()).includes(s.loot.name));await inspect('equipment compare');g=await command(g,'collectLoot','bag');const saved=g.export();await page.reload();assert.equal((await current()).export(),saved,'item/reward persists exactly');}
   else if(s.scene==='chapter'){if(g.p2Reaction()){assert((await page.locator('#bf-play').innerText()).includes(g.p2Reaction()),'past choice actually appears');reaction=true;fs.mkdirSync('screenshots/p2',{recursive:true});await page.screenshot({path:`screenshots/p2/${engine}-${width}-${ev.id}-${choice}-reaction.png`,fullPage:true});}g=await command(g,'chapterChoice',0);}
   else if(s.scene==='map')g=await command(g,'choose',0);else if(['reward','merchant'].includes(s.scene))g=await command(g,'nextEncounter');else if(s.scene==='midboss')g=await command(g,'faceMidboss');
   else if(s.scene==='npc'){assert((await page.locator('#bf-play').innerText()).includes(g.p2Reaction())||!g.p2Reaction());g=await command(g,'npcChoice',g.getAffinity(s.thread)>=40?3:0);}
   else if(s.scene==='event')g=await command(g,'event',g.eventChoices().findIndex(c=>g.canPay(c.cost)));
   else if(s.scene==='camp'){g=await command(g,'rest');g=await command(g,'enterArea',ev.region);}
   else throw Error('Unexpected P2 journey '+s.scene);
  }
  assert(battle&&gear&&reaction,'choice→battle→gear→reconnected story');assert.equal(g.s.decisions[ev.key],recorded);await inspect('subsequent reaction');fs.mkdirSync('screenshots/p2',{recursive:true});await page.screenshot({path:`screenshots/p2/${engine}-${width}-${ev.id}-${choice}.png`,fullPage:true});checks.push({width,event:ev.id,choice,recorded,battle,gear,reaction,saveExact:true,fixtureCommands:fixtures[ev.region].commands});
 }
 // Real campaign inventory supplies enough gold; no synthetic currency grants.
 for(const slot of ['weapon','armor','charm']){const h=Game.load(fixtures[5].code);h.retreat();const s=h.export();await restore(s);let g=await current();assert(g.s.gold>=55);g.s.scene='merchant';/* merchant UI fixture only; money/equipment are actual */await restore(g.export());const gold=g.s.gold;g=await command(g,'buy','gear-'+slot);assert.equal(g.s.gold,gold-55);assert.equal(g.s.loot.slot,slot);await inspect('targeted '+slot);g=await command(g,'collectLoot','bag');await page.reload();assert.equal((await current()).export(),g.export());checks.push({width,slot,price:55,saveExact:true});}
 assert.deepEqual(errors,[]);await context.close();
}}finally{await browser.close();}fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+`/ui-${engine}.json`,JSON.stringify({status:'PASS',engine,base,checks,errors:0,limitations:['Mobile emulation, not physical devices.','Regional imports were reached by a real campaign; only merchant scene uses a UI fixture.']},null,2)+'\n');console.log(`PASS P2 ${engine}: ${checks.length} event/choice/battle/gear/reconnect/reaction and targeted-box checks; zero console/runtime errors`);
})().catch(e=>{console.error(e);process.exit(1);});
