const assert=require('node:assert/strict'),fs=require('fs');const {Game}=require('./test-support.cjs');
const fresh=(seed=1)=>{const g=new Game(seed);g.start('warrior');return g;};
function win(g,boss=false,elite=false){g.travel(g.s.cleared.length);g.fight(boss,elite);g.s.enemy.hp=1;g.s.hp=g.maxHp();g.s.mp=g.maxMp();const before={gold:g.s.gold,xp:g.s.xp,sigils:g.s.sigils,cleared:[...g.s.cleared]};g.act('attack');assert(['loot','reward'].includes(g.s.scene));assert.deepEqual({gold:g.s.gold,xp:g.s.xp,sigils:g.s.sigils,cleared:g.s.cleared},before);assert.equal(g.s.rewardState.claimed,false);const code=g.export(),h=Game.load(code);assert.equal(h.export(),code);assert.deepEqual(h.rng.getState(),g.rng.getState());return {g,h,before};}
let count=0;for(const boss of [false,true])for(const elite of [false,true])for(const mode of ['equip','bag','sell'])for(const seed of [1,2,77]){const {g,h}=win(fresh(seed),boss,elite);const v=g.s.resultVisual,after={...g.s.rewardState.after};assert(v&&v.category===(boss?'bosses':'enemies'));for(const x of [g,h]){if(x.s.scene==='loot')x.collectLoot(mode);else x.nextEncounter();assert.equal(x.s.rewardState.claimed,true);assert(x.s.gold>=after.gold);assert.equal(x.s.xp,after.xp);const code=x.export();assert.equal(x.claimVictory(),false);assert.equal(x.export(),code);assert.equal(Game.load(code).export(),code);}assert.equal(g.export(),h.export());count++;}
for(const area of [2,5]){let g=fresh();g.s.cleared=Array.from({length:area},(_,i)=>i);g.travel(area);g.s.step=10;g.routes();g.nextEncounter();assert.equal(g.s.scene,'midboss');assert.equal(g.s.step,10);let h=Game.load(g.export());h.skipMidboss();assert.equal(h.s.step,11);assert.equal(h.s.midbosses.length,0);h.nextEncounter();assert.equal(h.s.step,12);assert.equal(h.s.scene,'reward');g.faceMidboss();assert(g.s.enemy.midboss);g.s.enemy.hp=1;g.act('attack');assert(g.s.midbosses.includes(area));assert.equal(g.s.cleared.length,area);if(g.s.scene==='loot')g.collectLoot('bag');else g.nextEncounter();assert.equal(g.s.scene,'reward');assert.equal(g.s.step,12);Game.load(g.export());}
let g=fresh();g.enterArea(0);assert.equal(g.s.scene,'chapter');g.chapterChoice(0);assert.equal(g.s.scene,'reward');assert.equal(g.s.resultVisual.category,'story');const paused=g.export();assert.equal(Game.load(paused).export(),paused);g.nextEncounter();assert.notEqual(g.s.scene,'map');
// Legacy reward/loot were credited already: no new pending rewards and no extra grant.
g=fresh();g.s.scene='loot';g.s.gold=123;g.s.loot=g.makeGear('normal');g.s.pending='reward';const payload=JSON.parse(global.LZString.decompressFromBase64(g.export().slice(4)));for(const k of ['rewardState','resultVisual','resultKind','journeySeq','returnAfterResult','acceptMidboss'])delete payload.state[k];for(const format of ['black-forest-v2','black-forest-v3']){const old=Game.load(JSON.stringify({...payload,format}));assert.equal(old.s.rewardState,null);old.takeLoot('bag');assert.equal(old.s.gold,123);assert.equal(Game.load(old.export()).export(),old.export());}
// Pending rewards may not bypass validation or be claimed after leaving the result.
g=win(fresh()).g;const bad=JSON.parse(global.LZString.decompressFromBase64(g.export().slice(4)));bad.state.rewardState.after.gold=-1;assert.throws(()=>Game.load(JSON.stringify(bad)));bad.state.rewardState.after.gold=999;bad.state.scene='camp';assert.throws(()=>Game.load(JSON.stringify(bad)));
// Retained checkpoints keep exactly the routes and RNG until the player resumes.
g=fresh();g.travel(0);g.s.step=4;g.s.scene='reward';g.pauseChapter();const checkpoint=Game.load(g.export()),routes=[...checkpoint.s.checkpoint.routes],rng=[...checkpoint.rng.getState()];checkpoint.resumeChapter();assert.deepEqual(checkpoint.s.routes,routes);assert.deepEqual(checkpoint.rng.getState(),rng);checkpoint.nextEncounter();assert.notEqual(checkpoint.s.scene,'map');
// Camp conversations while a route is retained must remain reloadable at the result.
let checkpointConversationCases=0;
for(const step of [4,8,12])for(const kind of ['npc','dialogue','bond']){
 const x=fresh();x.s.cleared=[0,1];x.travel(2);x.s.step=step;x.s.scene='reward';x.pauseChapter();
 const retained=JSON.parse(JSON.stringify(x.s.checkpoint));
 if(kind==='npc'){x.meetNpc('alice');x.npcChoice(0);}
 if(kind==='dialogue'){x.thread('alice');x.dialogue(0);}
 if(kind==='bond'){x.s.threads.alice=2;x.addAffinity('alice',80);x.bondQuest('alice');x.bondChoice(1);}
 assert.equal(x.s.scene,'reward');assert.equal(x.s.returnAfterResult,'camp');
 const code=x.export(),reloaded=Game.load(code);assert.equal(reloaded.export(),code);
 const rng=reloaded.rng.getState();reloaded.pauseChapter();assert.equal(reloaded.export(),code,'result must not overwrite the retained route');
 reloaded.nextEncounter();assert.equal(reloaded.s.scene,'camp');assert.deepEqual(reloaded.s.checkpoint,retained);assert.deepEqual(reloaded.rng.getState(),rng);
 const camp=Game.load(reloaded.export());camp.resumeJourney();assert.equal(camp.s.checkpoint,null);assert.notEqual(camp.s.scene,'camp');Game.load(camp.export());
 const invalid=JSON.parse(global.LZString.decompressFromBase64(code.slice(4)));invalid.state.returnAfterResult=null;assert.throws(()=>Game.load(JSON.stringify(invalid)),'unrelated reward cannot contain a checkpoint');
 checkpointConversationCases++;
}
const ui=fs.readFileSync('ui.js','utf8');assert(!ui.includes('scheduleAutoEncounter')&&!ui.includes('requestAnimationFrame'));assert(ui.includes('lastJourneyAction')&&ui.includes('isConnected'));const report={rewardCases:count,checkpointConversationCases,reloadDeterminism:'PASS',claimOnce:'PASS',legacyCreditedLoot:'PASS',optionalMidboss:'PASS',playerControlled:'PASS',checkpointPreservation:'PASS',pendingValidation:'PASS'};fs.writeFileSync('journey-results.json',JSON.stringify(report,null,2)+'\n');console.log('PASS Journey: '+JSON.stringify(report));
