const assert=require('node:assert/strict');const {Game,JOBS,ITEMS,EVENTS,MELEE,SWORDS,WEIGHTS}=require('./test-support.cjs');const results=[];
function game(job='warrior',seed=123){const g=new Game(seed,{unlocked:Object.keys(JOBS).filter(k=>JOBS[k].hidden)});g.start('warrior');g.s.job=job;g.s.career=BFContent.newCareer(job);g.s.career.hiddenPath=!!JOBS[job].hidden;g.s.hp=g.maxHp();g.s.mp=g.maxMp();return g}
assert.equal(Object.keys(JOBS).length,114);assert.equal(ITEMS.length,1000);assert.equal(MELEE.length,20);assert.equal(SWORDS.length,50);assert.deepEqual([0,2,3,4].map(x=>SWORDS.filter(i=>i.fixedGrade===x).length),[20,15,10,5]);assert.equal(new Set(ITEMS.map(i=>i.name)).size,ITEMS.length);assert.equal(new Set(Object.values(JOBS).map(i=>i.name)).size,Object.keys(JOBS).length);results.push(`DB: 직업 ${Object.keys(JOBS).length}, 장비 ${ITEMS.length}, 도검 20/15/10/5, 중복 이름 없음`);
let g=new Game();assert.equal(g.s.offers.length,6);assert.equal(Game.load(g.export()).export(),g.export());g.start(g.s.offers[0]);let clone=Game.load(g.export());assert.equal(clone.export(),g.export());g.travel(0);g.fight();clone=Game.load(g.export());g.act('attack');clone.act('attack');assert.equal(g.export(),clone.export());results.push('신규·전투 저장 및 압축·난수 상태 정확 복원');
const old=new BlackForestLegacy.Game();old.start('warrior');old.s.gold=123;const migrated=Game.load(old.export());assert.equal(migrated.s.gold,123);assert.equal(migrated.s.level,old.s.level);assert.equal(migrated.s.version,3);Game.load(migrated.export());results.push('v1 → v3 저장 호환');
g=game();g.s.scene='battle';g.fight(true);g.s.mp=0;let before=g.export();g.act('skill');assert.equal(g.export(),before);g.s.potions=0;before=g.export();g.act('potion');assert.equal(g.export(),before);g.s.enemy.intent='heavy';const preview=g.damagePreview(),hp=g.s.hp;g.act('defend');assert.equal(hp-g.s.hp,Math.max(1,Math.floor(preview*.3)));results.push('MP·물약 부족 차단 / 방어 계산');
g=game();g.s.pity=29;assert(g.makeGear().grade>=4);assert.equal(g.s.pity,0);g.s.gold=100000;g.s.ore=10000;g.s.weapon.plus=7;g.s.weapon.fails=2;g.upgrade('weapon');assert.equal(g.s.weapon.plus,8);results.push('30번째 전설 보정 / 강화 연속 실패 보정');
g=game();g.travel(0);g.s.step=1;g.s.scene='map';g.s.secretPity=11;g.routes();assert.deepEqual(g.s.routes,['secret']);g.choose(0);assert.equal(g.s.sigils,1);assert.equal(g.s.scene,'loot');results.push('랜덤 인카운트 단일 경로·비밀 보정·각성 인장·장비 지급');g=game();g.travel(0);g.s.step=1;g.s.scene='reward';const autoTurns=g.s.turns;g.nextEncounter();assert.notEqual(g.s.scene,'map','nextEncounter must skip the map stop');assert(g.s.turns>autoTurns,'nextEncounter must trigger the next encounter');results.push('결과 확인 행동 → 다음 상황 단일 생성');
for(const [id,j] of Object.entries(JOBS).filter(([,j])=>j.hidden)){g=game();g.s.unlocked=[];g.s.sigils=2;g.s.mercy=3;g.s.cleared=[0,1,2,3];g.s.level=8;g.s.kills=20;g.s.elites=3;g.s.lowhpWins=2;g.s.weapon.plus=3;g.s.crafts=3;g.s.caches=4;g.s.rareFinds=2;g.s.secrets=2;for(const npc of Object.keys(BFContent.NPCS)){g.addAffinity(npc,100-g.getAffinity(npc));g.s.storyFlags[npc+'_seen']=true;}g.s.endings=[0];g.s.collection=ITEMS.slice(0,150).map(d=>d.id);assert(g.eligible(id),id);g.awaken(id);assert(g.s.unlocked.includes(id));g.awaken(id);assert.equal(g.s.sigils,1);g.changeJob(id);assert.equal(g.s.job,id);g.travel(0);g.fight();g.act('skill');assert(Number.isFinite(g.s.hp));Game.load(g.export())}results.push('히든 14종 조건·해금·중복 소모 방지·전직·스킬');
for(const event of EVENTS)for(let choice=0;choice<event.choices.length;choice++){g=game();Object.assign(g.s,{gold:500,ore:20,wood:20,herb:20,potions:20,scene:'event',eventId:event.id});if(event.region!==undefined){g.s.area=event.region;g.s.storyFlags['chapter_'+event.region+'_seen']=true;}g.event(choice);assert(['loot','reward','battle'].includes(g.s.scene));Game.load(g.export())}results.push('기존 18개 양쪽 선택 36개 + 지역 이벤트 3개의 전체 9선택; P2 전수는 test-p2.cjs');
for(const order of [['alice','adam','ahab'],['ahab','alice','adam']]){g=game();g.s.cleared=[0];for(const id of order){g.thread(id);g.dialogue(0);if(g.s.returnAfterResult)g.advance();g.thread(id);g.dialogue(0);if(g.s.returnAfterResult)g.advance();}assert.equal(g.s.affection.alice,70);assert.equal(g.s.affection.adam,70);assert.equal(g.s.affection.ahab,40);assert.equal(g.s.factions.lantern,6);assert.equal(g.s.sigils,3);const before=g.export();g.thread('alice');assert.equal(g.export(),before);Game.load(g.export())}results.push('비선형 퀘스트 순서·호감도 보상·중복 완료 방지');
for(const source of Object.keys(WEIGHTS)){g=game();const counts=Array(6).fill(0),N=60000;for(let i=0;i<N;i++){g.s.pity=0;counts[g.rollGrade(source)]++}const measured=counts.map(n=>n/N*100);measured.forEach((n,i)=>assert(Math.abs(n-WEIGHTS[source][i])<.65,source+' distribution '+i));results.push(`확률 ${source}: ${measured.map(n=>n.toFixed(2)+'%').join(' / ')} (n=${N})`)}
let battles=0,deaths=0;for(const id of Object.keys(JOBS)){for(let seed=1;seed<=6;seed++){g=game(id,seed);let count=0;while(g.s.scene!=='ending'&&count++<3000){const s=g.s;if(s.scene==='camp'){g.rest();for(const q of g.quests())g.claim(q.id);while(s.herb>=3)g.craft();if(s.potions<4&&s.gold>=16)g.buy('potion');g.upgrade('weapon');g.upgrade('armor');g.campUp();if(s.cleared.length>=1)for(const t of ['alice','adam','ahab'])while(s.threads[t]<2){g.thread(t);g.dialogue(0);if(g.s.returnAfterResult)g.advance();}g.travel(Math.min(7,s.cleared.length));}else if(s.scene==='map'){let i=s.routes.indexOf(s.hp<g.maxHp()*.65?'shrine':'battle');if(i<0)i=s.routes.indexOf('secret');if(i<0)i=s.routes.indexOf('cache');g.choose(i<0?0:i)}else if(s.scene==='battle'){battles++;if(s.hp<Math.max(gameDamage(g)+8,g.maxHp()*.27)&&s.potions)g.act('potion');else if(s.enemy.intent==='heavy')g.act('defend');else if(s.mp>=g.skillCost())g.act('skill');else g.act('attack')}else if(s.scene==='loot'){const d=s.loot,old=s[d.slot];g.takeLoot(d.power+d.grade+d.affixes.reduce((n,a)=>n+a.value*.2,0)>old.power+old.plus*(d.slot==='weapon'?2:1)+old.grade?'equip':'sell')}else if(s.scene==='reward'||s.scene==='merchant')g.advance();else if(s.scene==='event'){g.event(g.eventChoices().findIndex(c=>g.canPay(c.cost)))}else if(s.scene==='dead'){deaths++;g.revive()}else if(s.scene==='midboss')g.faceMidboss();else if(s.scene==='chapter')g.chapterChoice(0);else if(s.scene==='npc'){g.npcChoice(0);if(g.s.returnAfterResult)g.advance();}else if(s.scene==='final')g.finish(2);else throw Error('Unexpected '+s.scene);assert(s.hp>=0&&s.mp>=0&&s.gold>=0);if(count%20===0)Game.load(g.export());}assert.equal(g.s.scene,'ending',`${id} seed ${seed} stuck ${g.s.scene}`)}}
results.push(`전 직업 114 × 6시드 = 684 캠페인 완주; 전투 행동 ${battles}, 부활 ${deaths} (각 직업 직접 지정한 전투 회귀 테스트; 일반 시작 규칙을 우회한 테스트 fixture)`);
function gameDamage(g){return g.damagePreview()}
console.log(results.join('\n'));require('fs').writeFileSync(__dirname+'/test-results.txt',results.join('\n'));
