const fs=require('node:fs'),assert=require('node:assert/strict'),{world,plain,baseline}=require('./p3-test-support.cjs');
const before=world(true),now=world(),C=now.BFContent,G=now.BlackForest.Game,out=process.env.BF_P3_OUT||'docs/p3';fs.mkdirSync(out,{recursive:true});let checks=0,restores=0;const test=(label,fn)=>{fn();checks++;};
const fresh=()=>{const g=new G(17);g.start('warrior');return g;};
const purse=g=>plain({gold:g.s.gold,ore:g.s.ore,wood:g.s.wood,herb:g.s.herb,potions:g.s.potions,crafts:g.s.crafts,collection:g.s.collection,bag:g.s.bag,loot:g.s.loot,rng:g.rng.getState()});
const restore=g=>{const code=g.export();assert.equal(G.load(code).export(),code);restores++;};
const gear=(g,id)=>{const b=C.ITEMS.find(x=>x.id===id);return {...plain(b),power:b.basePower+Math.floor((b.areaScale||0)*g.s.area),grade:b.fixedGrade,plus:0,fails:0,affixes:plain(b.fixedAffixes||[{id:b.fixed,value:b.fixedValue}])};};
function budget(g){g.s.cleared=[0,1,2,3];g.s.area=4;g.s.gold=10000;g.s.ore=1000;g.s.wood=1000;g.s.herb=1000;}
test('all pre-existing definitions',()=>{for(const k of ['JOBS','ITEMS','EVENTS','CHAPTERS','CHAPTER_DECISIONS','AFFIXES','WEIGHTS','NPCS'])assert.deepEqual(plain(C[k]),plain(before.BFContent[k]),k+' unchanged');});
test('old archives exact',()=>{for(const file of ['fixtures/p1-pre-saves.json','fixtures/p2-pre-saves.json','fixtures/p3-pre-saves.json'])for(const row of require('./'+file).saves){assert.equal(G.load(row.code).export(),row.code,file+' '+row.id);restores++;}});
let appraisals=0;for(const d of C.ITEMS)for(const area of [0,4,7])for(const plus of [0,3,8])test('bounded value '+d.id,()=>{const g=fresh(),grade=d.fixedGrade??(d.unique?4:1),item={...plain(d),power:(d.basePower??8)+Math.floor((d.areaScale||0)*area),grade,plus,affixes:plain(d.fixedAffixes||[])};const p=g.price(item);assert(Number.isSafeInteger(p)&&p>=8&&p<=50+plus*2);assert(g.price({...item,power:item.power+3})>=p);assert(g.price({...item,affixes:[...item.affixes,{id:'mana',value:3}]})>=p);assert(g.price({...item,plus:Math.min(8,plus+1)})-p<=2);appraisals++;});
let craftCases=0;for(const r of C.P3_RECIPES){
 test('preview/cancel '+r.id,()=>{const g=fresh();budget(g);const code=g.export();const row=g.craftingRecipes().find(x=>x.id===r.id);assert(row.available&&row.canAfford);assert.equal(g.export(),code,'preview has no cost/RNG');assert(C.ITEMS.some(d=>d.id===row.gear.id&&d.slot===row.gear.slot));assert(g.price(row.gear)<r.cost.gold,'craft sale cannot refund gold');assert(2+row.gear.grade<r.cost.ore,'craft salvage cannot refund ore');});
 for(const resource of Object.keys(r.cost))test('missing '+resource+' '+r.id,()=>{const g=fresh();budget(g);g.s[resource]=r.cost[resource]-1;const old=purse(g);g.craftGear(r.id);assert.deepEqual(purse(g),old);assert.equal(g.s.scene,'camp');});
 test('recipe threshold '+r.id,()=>{const g=fresh();budget(g);g.s.cleared=g.s.cleared.slice(0,r.gate-1);const old=purse(g);g.craftGear(r.id);assert.deepEqual(purse(g),old);});
 for(const mode of ['bag','sell','equip'])test('craft '+r.id+' '+mode,()=>{const g=fresh();budget(g);const old=purse(g),expected=g.recipeGear(r.id);g.craftGear(r.id);assert.equal(g.s.scene,'loot');assert.deepEqual(plain(g.s.loot),plain(expected));for(const [k,v]of Object.entries(r.cost))assert.equal(g.s[k],old[k]-v);assert.equal(g.s.crafts,old.crafts+1);assert.equal(g.s.collection.filter(id=>id===r.id).length,1);restore(g);const code=g.export();g.craftGear(r.id);assert.equal(g.export(),code,'double call no result/cost duplication');g.takeLoot(mode);assert.equal(g.s.scene,'camp');restore(g);const end=g.export();g.takeLoot(mode);assert.equal(g.export(),end,'double receipt inert');if(mode==='sell')assert(g.s.gold<old.gold);if(mode==='bag')assert.equal(g.s.bag.at(-1).id,r.id);if(mode==='equip')assert.equal(g.s[expected.slot].id,r.id);craftCases++;});
 test('forge/salvage/reforge '+r.id,()=>{const g=fresh();budget(g);const gold=g.s.gold,ore=g.s.ore;g.craftGear(r.id);g.takeLoot('bag');g.salvage(g.s.bag.length-1);assert(g.s.gold<gold&&g.s.ore<ore);const before=purse(g);g.s.ore=r.cost.ore-1;const no=purse(g);g.craftGear(r.id);assert.deepEqual(purse(g),no);});
}
test('invalid recipes and wallets',()=>{for(const id of ['not-an-item','__proto__',null,{},1]){const g=fresh();budget(g);const p=purse(g);g.craftGear(id);assert.deepEqual(purse(g),p);}for(const value of [-1,NaN,Infinity,1e9+1]){const g=fresh();budget(g);g.s.gold=value;const p=purse(g);g.craftGear(C.P3_RECIPES[0].id);assert.deepEqual(purse(g),p);g.buy('gear-weapon');assert.deepEqual(purse(g),p);assert.throws(()=>G.load(g.export()),'invalid gold cannot be imported');}});
let purchases=0;for(const slot of ['weapon','armor','charm'])test('box/resale '+slot,()=>{const g=fresh();g.s.gold=30000;g.s.area=7;for(let n=0;n<300;n++){const old=g.s.gold;g.buy('gear-'+slot);assert.equal(g.s.gold,old-55);assert(g.s.loot.slot===slot&&g.price(g.s.loot)<=50);const once=g.export();g.buy('gear-'+slot);assert.equal(g.export(),once);g.takeLoot('sell');assert(g.s.gold<=old-5);purchases++;}});
test('wallet ceiling preserves gear and existing gold',()=>{const g=fresh();g.s.gold=1e9;g.s.bag=[gear(g,'set_charm_1')];g.sellBag(0);assert.equal(g.s.gold,1e9);assert.equal(g.s.bag.length,1);assert(g.grant({gold:100}).includes('골드 +0'));assert.equal(g.s.gold,1e9);g.fight(false);g.s.enemy.hp=1;g.act('attack');if(g.s.rewardState){assert.equal(g.s.rewardState.after.gold,1e9);assert.equal(g.s.rewardState.rewards.gold,0);}if(g.s.scene==='loot')g.takeLoot('bag');else g.advance();assert.equal(g.s.gold,1e9);restore(g);});
test('cache wallet ceiling remains loadable',()=>{const g=fresh();g.s.gold=1e9;g.s.scene='map';g.s.routes=['cache'];g.chance=()=>false;g.choose(0);assert.equal(g.s.gold,1e9);restore(g);});
if(process.argv.includes('--economy-crafting')){console.log(`PASS P3 economy/crafting: ${checks} checks; ${appraisals} appraisals; ${craftCases} atomic craft receipts; ${purchases} loss-making buy/sell cycles; ${restores} restores`);process.exit(0);}
// Upgrade probabilities/cap/failure pity are inherited, costs are independently bounded.
let upgradeCases=0;for(const slot of ['weapon','armor','charm'])for(const grade of [0,1,2,5])for(let plus=0;plus<8;plus++)test('upgrade '+slot+'/'+grade+'/'+plus,()=>{const g=fresh();budget(g);const d=g.s[slot];d.grade=grade;d.plus=plus;const cost=g.upgradeCost(slot),price=g.price(d);assert(cost.gold>=15&&cost.ore>=2);assert.equal(g.upgradeChance(slot),plus<5?1:[.8,.6,.4][plus-5]);g.chance=()=>true;const old=g.s.gold;g.upgrade(slot);assert.equal(d.plus,plus+1);assert.equal(g.s.gold,old-cost.gold);assert(g.price(d)-price<cost.gold,'upgrade sale cannot refund');restore(g);upgradeCases++;});
test('failure and guaranteed retry',()=>{const g=fresh();budget(g);g.s.weapon.plus=5;g.chance=()=>false;g.upgrade('weapon');g.upgrade('weapon');assert.equal(g.s.weapon.plus,5);assert.equal(g.s.weapon.fails,2);assert.equal(g.upgradeChance('weapon'),1);restore(g);g.chance=p=>p===1;g.upgrade('weapon');assert.equal(g.s.weapon.plus,6);assert.equal(g.s.weapon.fails,0);g.s.weapon.plus=8;const p=purse(g);g.upgrade('weapon');assert.deepEqual(purse(g),p);assert(g.s.message.includes('더 이상'));});
test('insufficient upgrade atomic',()=>{for(const k of ['gold','ore']){const g=fresh();budget(g);g.s[k]=0;const p=purse(g),gearBefore=plain(g.s.weapon);g.upgrade('weapon');assert.deepEqual(purse(g),p);assert.deepEqual(plain(g.s.weapon),gearBefore);assert(g.s.message.includes('부족'));}});
let tuningCases=0;for(const slot of ['weapon','armor','charm'])test('purpose tuning '+slot,()=>{const g=fresh();budget(g);const d=gear(g,{weapon:'lit_sword_22',armor:'set_armor_8',charm:'set_charm_2'}[slot]);g.s[slot]=d;const options=g.tuningOptions(slot);for(const o of options){const h=G.load(g.export()),old=plain(h.s[slot]),gold=h.s.gold;h.tuneGear(o.key);assert.deepEqual(plain(h.s[slot].affixes.slice(0,-1)),old.affixes.slice(0,-1));assert.equal(h.s[slot].plus,old.plus);assert.equal(h.s[slot].affixes.at(-1).id,o.id);assert.equal(h.s.gold,gold-o.cost.gold);assert(h.price(h.s[slot])-h.price(old)<o.cost.gold);restore(h);const p=purse(h),after=plain(h.s[slot]);h.tuneGear(o.key);assert.deepEqual(purse(h),p);assert.deepEqual(plain(h.s[slot]),after);tuningCases++;}const o=options[0],p=purse(g);g.s.gold=0;const poor=purse(g);g.tuneGear(o.key);assert.deepEqual(purse(g),poor);});
let setCases=0;for(const [index,name]of [[20,'토끼굴'],[7,'산초의 귀환길'],[13,'노트르담의 종'],[1,'하트 법정']])for(const count of [0,1,2,3])test('derived set '+name+'/'+count,()=>{const g=fresh();budget(g);for(const slot of ['weapon','armor','charm'].slice(0,count))g.s[slot]=gear(g,'set_'+slot+'_'+index);const sets=g.activeSets();assert.equal(sets[0]?.count||0,count);const code=g.export();restore(g);assert.equal(g.export(),code,'no set cache is serialized');const raw=id=>g.equipment().reduce((n,d)=>n+d.affixes.filter(a=>a.id===id).reduce((n,a)=>n+a.value,0),0);
 if(name==='토끼굴')assert.equal(g.bonus('mana')-raw('mana'),count>=2?2:0);
 if(name==='산초의 귀환길')assert.equal(g.bonus('thorns')-raw('thorns'),count>=2?1:0);
 if(name==='하트 법정')assert.equal(g.bonus('critical')-raw('critical'),count>=2?2:0);
 if(count===3){g.s.hp=Math.floor(g.maxHp()/2);if(name==='산초의 귀환길')assert.equal(g.bonus('leech')-raw('leech'),2);if(name==='노트르담의 종'){assert.equal(g.bonus('defense')-raw('defense'),1);assert.equal(g.bonus('dodge')-raw('dodge'),2);}if(name==='토끼굴'){g.fight(false);assert.equal(g.bonus('dodge')-raw('dodge'),3);g.s.enemy.turn=1;assert.equal(g.bonus('dodge')-raw('dodge'),0);}}
 if(count){g.s.scene='camp';g.s.enemy=null;const d=g.s.weapon;g.s.bag=[plain(new G(17).s.weapon)];g.equipBag(0);assert.equal(g.activeSets()[0]?.count||0,count-1);g.equipBag(0);assert.equal(g.activeSets()[0]?.count||0,count);setCases++;}});
test('canonical IDs prevent spoofed/duplicate set pieces',()=>{const g=fresh();budget(g);const d=gear(g,'set_weapon_7');g.s.weapon=d;g.s.armor={...plain(d),slot:'armor'};g.s.charm={...plain(d),slot:'charm'};assert.equal(g.activeSets()[0].count,1);g.s.weapon={...g.s.weapon,id:'unknown',set:'산초의 귀환길'};assert.equal(g.activeSets().length,0);});
const setProbes=[];test('rabbit first-hit avoidance is used by combat',()=>{const a=new before.BlackForest.Game(17);a.start('warrior');a.s.area=0;for(const slot of ['weapon','armor','charm'])a.s[slot]=gear(a,'set_'+slot+'_20');a.s.hp=a.maxHp();a.s.mp=0;const b=G.load(a.export());for(const g of [a,b]){g.fight(false);g.s.enemy.hp=g.s.enemy.maxHp=500;g.s.enemy.intent='attack';g.chance=p=>p>.075;}a.act('defend');b.act('defend');assert(b.s.message.includes('회피'));assert(!a.s.message.includes('회피'));assert(b.s.hp>a.s.hp);setProbes.push({set:'토끼굴',beforeHp:a.s.hp,afterHp:b.s.hp,firstTurn:true});});
 test('sancho reflection is used by combat',()=>{const a=new before.BlackForest.Game(17);a.start('warrior');for(const slot of ['weapon','armor'])a.s[slot]=gear(a,'set_'+slot+'_7');a.s.hp=a.maxHp();const b=G.load(a.export());for(const g of [a,b]){g.fight(false);g.s.enemy.hp=g.s.enemy.maxHp=500;g.s.enemy.intent='attack';g.chance=()=>false;}a.act('defend');b.act('defend');assert.equal(a.s.enemy.hp-b.s.enemy.hp,1);setProbes.push({set:'산초의 귀환길',beforeEnemyHp:a.s.enemy.hp,afterEnemyHp:b.s.enemy.hp});});
fs.writeFileSync(out+'/set-effect-probes.json',JSON.stringify({status:'PASS',method:'Controlled durable enemy and probability threshold probes validate combat execution; not natural RNG frequency or unlock claims.',probes:setProbes},null,2)+'\n');
let endingCases=0;for(const choice of [0,1,2])for(const mercy of [0,5])test('existing ending threshold '+choice+'/'+mercy,()=>{const a=new before.BlackForest.Game(17);a.start('warrior');a.s.scene='final';a.s.mercy=mercy;const b=G.load(a.export());a.finish(choice);b.finish(choice);assert.equal(b.s.scene,a.s.scene);assert.equal(b.s.ending,a.s.ending);assert.deepEqual(plain(b.s.endings),plain(a.s.endings));restore(b);const code=b.export();b.finish(choice);assert.equal(b.export(),code);endingCases++;});
let epilogues=0;for(const choice of [0,1,2])for(const bell of ['read:success','read:failure','trail:success','trail:failure','copy:success'])for(const water of ['share:success','trail:success','record:success'])for(const margin of ['read:success','read:failure','mend:success','copy:success'])test('conditional future',()=>{const g=fresh();g.s.scene='final';g.s.mercy=5;g.s.decisions={p2_bell:bell,p2_water:water,p2_margin:margin};g.finish(choice);const r=g.endingReport();assert.equal(r.regions.length,3);assert.equal(new Set(r.regions.map(x=>x.text)).size,3);for(const x of r.regions)assert(x.text.length>25&&!/p2_|success|failure|chapter_|set_/.test(x.text+x.choice));assert.deepEqual(plain(G.load(g.export()).endingReport()),plain(r));restore(g);epilogues++;});
test('older endings omit unexperienced region incidents',()=>{const g=fresh();g.s.scene='final';g.finish(0);assert.equal(g.endingReport().regions.length,0);});
fs.writeFileSync(out+'/automatic-qa.json',JSON.stringify({status:'PASS',baseline,checks,appraisals,craftCases,purchases,upgradeCases,tuningCases,setCases,endingConditions:endingCases,conditionalEndingCombinations:epilogues,restores,existingDefinitions:{jobs:114,items:1000,events:21},recipes:15,sets:4,saveSchema:'BF3 unchanged; no required crafting/set cache',limitations:['Controlled fixtures do not prove human demand or every build balance.']},null,2)+'\n');
console.log(`PASS P3: ${checks} checks; ${restores} exact restores; ${craftCases} craft receipts; ${upgradeCases} upgrades; ${tuningCases} tunes; ${endingCases} old ending conditions; ${epilogues} conditional futures`);
