/* Browser acceptance suite. Run in a supported portable QA environment. */
const assert=require('node:assert/strict'),fs=require('node:fs');
const pw=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');const {Game,JOBS,ITEMS}=require('./test-support.cjs');
const viewports=[{width:320,height:568},{width:360,height:800},{width:370,height:800},{width:375,height:812},{width:390,height:844},{width:430,height:932},{width:768,height:1024},{width:1280,height:900}];
async function suite(touch=false){const browser=await pw[process.env.BF_BROWSER||'chromium'].launch({headless:true,...(process.env.BF_CHROMIUM?{executablePath:process.env.BF_CHROMIUM}:{})});let report=[];try{
 for(const size of viewports){const context=await browser.newContext({viewport:size,hasTouch:touch,isMobile:touch&&size.width<768,colorScheme:size.width===430?'dark':'light'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const activate=async locator=>touch?locator.tap():locator.click();
 await page.goto(process.env.BF_QA_URL||'file://'+__dirname+'/black-forest.html');assert.equal(await page.locator('[data-cmd="start"]').count(),6);await activate(page.locator('[data-cmd="start"][data-arg="warrior"]'));const g=new Game(123);g.start('warrior');g.s.level=10;g.s.cleared=[0,1,2,3];g.s.career.mastery.warrior=20;g.s.sigils=5;g.s.gold=1500;g.s.ore=200;g.s.herb=30;g.s.wood=30;g.s.hp=g.maxHp();g.s.mp=g.maxMp();g.s.bag.push(g.makeGear('boss'));g.addAffinity('alice',50-g.getAffinity('alice'));
 const restore=async code=>{await activate(page.locator('[data-ui="save"]'));await page.locator('#bf-code').fill(code);await activate(page.locator('[data-ui="load"]'));await page.locator('#bf-panel').waitFor({state:'hidden'});};await restore(g.export());
 async function fit(screen){assert.equal(await page.locator('#bf-play img:visible,#bf-panel img:visible').evaluateAll(images=>images.filter(i=>i.complete&&!i.naturalWidth).length),0,screen+' broken image');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,screen+' page overflow '+size.width);for(const el of await page.locator('#bf-play img:visible,#bf-panel img:visible').all()){const box=await el.boundingBox();assert(box.width<=size.width&&box.x>=-1&&box.x+box.width<=size.width+1,screen+' image overflow');}if(await page.locator('#bf-panel').isVisible()){const box=await page.locator('#bf-panel').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=size.width+1&&box.y+box.height<=size.height+1,screen+' modal bounds');}}
 await fit('camp');for(const type of ['equipment','bag','workshop','jobs','codex','quests','story','save']){await activate(page.locator('[data-ui="'+type+'"]').first());await fit(type);assert.equal(await page.evaluate(()=>document.body.style.position),'fixed');assert.equal(await page.evaluate(()=>document.body.style.boxSizing),'border-box');await page.locator('#bf-panel').evaluate(el=>el.scrollTo(0,el.scrollHeight));await activate(page.locator('#bf-panel [data-ui="close"]'));assert.equal(await page.evaluate(()=>document.body.style.position),'');}
 await activate(page.locator('[data-ui="jobs"]').first());await page.locator('[data-filter="jobs:query"]').fill('잉크 견습생');assert(await page.locator('#bf-job-list [data-cmd="changeJob"]').isDisabled(),'cross-tree button must be locked');await page.keyboard.press('Escape');assert(await page.locator('#bf-panel').isHidden());
 await activate(page.locator('[data-ui="equipment"]').first());await activate(page.locator('[data-ui="gear-bag-0"]'));assert(await page.locator('.comparison').count());await activate(page.locator('[data-cmd="equipBag"]').first());assert(await page.locator('#bf-gear-feedback').isVisible());await activate(page.locator('#bf-panel [data-ui="close"]'));
 await activate(page.locator('[data-ui="story"]').first());await activate(page.locator('[data-cmd="thread"][data-arg="alice"]'));assert.equal(await page.locator('[data-cmd="dialogue"]').count(),4);assert(!(await page.locator('[data-cmd="dialogue"][data-arg="3"]').isDisabled()));await activate(page.locator('[data-cmd="dialogue"][data-arg="3"]'));await fit('story');
 g.travel(0);g.fight();await restore(g.export());await fit('battle');const codeBefore=await page.evaluate(()=>localStorage.getItem('black-forest-last-ember-v2'));const turns=Game.load(codeBefore).s.turns;await page.locator('[data-cmd="act"][data-arg="defend"]').scrollIntoViewIfNeeded();await activate(page.locator('[data-cmd="act"][data-arg="defend"]'));const codeAfter=await page.evaluate(()=>localStorage.getItem('black-forest-last-ember-v2'));assert.equal(Game.load(codeAfter).s.turns,turns+1,'one tap must run exactly one turn');await page.reload();assert.equal(await page.evaluate(()=>localStorage.getItem('black-forest-last-ember-v2')),codeAfter);await fit('reload');
 for(const button of await page.locator('#bf-play .actions button').all()){const box=await button.boundingBox();assert(box.width>=44&&box.height>=44,'touch target');}
 await activate(page.locator('[data-ui="save"]'));await page.locator('#bf-code').fill('{}');await activate(page.locator('[data-ui="load"]'));assert((await page.locator('#bf-code-status').textContent()).includes('실패'));assert.equal(await page.evaluate(()=>localStorage.getItem('black-forest-last-ember-v2')),codeAfter);await page.locator('#bf-code').fill(codeAfter);await activate(page.locator('[data-ui="load"]'));const longJob=Object.values(JOBS).filter(j=>!j.hidden).sort((a,b)=>b.name.length-a.name.length)[0];const longGear=ITEMS.slice().sort((a,b)=>b.name.length-a.name.length)[0];const named=new Game(123);named.start('warrior');named.s.job=longJob.id;named.s.career.current=longJob.id;named.s.career.history=[longJob.id];named.s.hp=named.maxHp();named.s.mp=named.maxMp();named.s.bag=[{...named.makeGear('boss'),id:longGear.id,name:longGear.name,slot:longGear.slot}];await restore(named.export());await fit('long class name');await activate(page.locator('[data-ui="equipment"]').first());await activate(page.locator('[data-ui="gear-bag-0"]'));await fit('long equipment name');await activate(page.locator('#bf-panel [data-ui="close"]'));assert.equal(errors.length,0,errors.join('\n'));fs.mkdirSync(__dirname+'/screenshots',{recursive:true});await page.screenshot({path:__dirname+'/screenshots/'+(process.env.BF_BROWSER||'chromium')+'-'+(touch?'touch':'click')+'-'+size.width+'.png'});report.push(`${size.width}x${size.height}: PASS ${touch?'touch':'click'} panels, gear, cross-tree lock, dialogue, battle, one tap/turn, reload, corrupt save, image bounds, longest class/equipment names, zero JS errors`);await context.close();}
 }finally{await browser.close();}console.log(report.join('\n'));fs.writeFileSync(__dirname+(touch?'/mobile-results-'+(process.env.BF_BROWSER||'chromium')+'.txt':'/browser-results.txt'),report.join('\n')+'\n');}
module.exports={suite};if(require.main===module)suite(false).catch(e=>{console.error(e);process.exit(1)});
