const fs=require('node:fs'),assert=require('node:assert/strict'),pw=require('playwright'),{Game}=require('./test-support.cjs'),fixtures=require('./p3-browser-fixtures.cjs').entries();
const engine=process.env.BF_BROWSER||'chromium',base=process.env.BF_QA_URL||'http://127.0.0.1:4183/',out=process.env.BF_P3_OUT||'docs/p3',key='black-forest-last-ember-v2';
(async()=>{const browser=await pw[engine].launch(require('./qa-browser.cjs')()),checks=[];try{for(const width of [360,390,430,768,1280]){const context=await browser.newContext({viewport:{width,height:900},hasTouch:true,isMobile:engine!=='firefox'&&width<768}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const tap=async l=>{await page.waitForTimeout(280);await l.scrollIntoViewIfNeeded();await l.tap();};
const current=async()=>Game.load(await page.evaluate(k=>localStorage.getItem(k),key));
const panel=async name=>tap(page.locator(`[data-ui="${name}"]`).first());
const close=async()=>{if(await page.locator('#bf-panel').isVisible())await panel('close');};
const restore=async code=>{await close();await panel('save');await page.locator('#bf-code').fill(code);await panel('load');assert.equal((await current()).export(),code);};
async function inspect(label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' viewport overflow');for(const l of await page.locator('#bf-play .actions button:visible,.p3-craft-preview[open] button:visible,.p3-tuning[open] button:visible').all()){const box=await l.boundingBox();assert(box.width>=40&&box.height>=44,label+' touch target');assert(await l.evaluate(e=>e.scrollWidth<=e.clientWidth+2),label+' clipped button');}for(const img of await page.locator('#bf-play img:visible,#bf-panel img:visible').all())await img.evaluate(e=>e.decode());assert.deepEqual(errors,[],label+' errors');}
async function command(g,name,arg){const expected=Game.load(g.export());expected[name](arg);assert.notEqual(expected.export(),g.export(),name+' progresses');await tap(page.locator(`[data-cmd="${name}"]`+(arg!==undefined?`[data-arg="${arg}"]`:'')).first());assert.equal((await current()).export(),expected.export(),name+' exact UI transaction');return expected;}
async function journeyStep(g){const s=g.s;if(s.scene==='battle')return command(g,'act',s.hp<g.maxHp()&&s.hp<Math.max(g.damagePreview()+8,g.maxHp()*.27)&&s.potions?'potion':s.enemy.intent==='heavy'&&g.damagePreview()>0?'defend':s.mp>=g.skillCost()?'skill':'attack');if(s.scene==='map')return command(g,'choose',0);if(s.scene==='chapter')return command(g,'chapterChoice',0);if(s.scene==='npc')return command(g,'npcChoice',g.getAffinity(s.thread)>=40?3:0);if(s.scene==='midboss')return command(g,'faceMidboss');if(s.scene==='loot')return command(g,'collectLoot','bag');if(s.scene==='event')return command(g,'event',g.eventChoices().findIndex(x=>g.canPay(x.cost)));if(['reward','merchant'].includes(s.scene))return command(g,'nextEncounter');if(s.scene==='camp'){g=await command(g,'rest');return command(g,s.checkpoint?'resumeJourney':'enterArea',s.checkpoint?undefined:Math.min(7,s.cleared.length));}throw Error('Unplanned UI path '+s.scene);}
await page.addInitScript(()=>{Date.now=()=>17;});await page.goto(base);await tap(page.locator('[data-cmd="start"][data-arg="warrior"]'));let g=await current();g=await command(g,'enterArea',0);let battle=false,loot=false,n=0;while(!(battle&&loot)&&n++<100){battle||=g.s.scene==='battle';if(g.s.scene==='loot'&&battle){loot=true;break;}g=await journeyStep(g);}assert(battle&&loot,'actual new-game exploration/battle/loot');await inspect('new game and reward');g=await command(g,'collectLoot','bag');await page.reload();assert.equal((await current()).export(),g.export());
await restore(fixtures.merchant.code);g=await current();g=await command(g,'buy','gear-armor');assert.equal(g.s.loot.slot,'armor');await inspect('shop and comparison');g=await command(g,'collectLoot','bag');
await restore(fixtures.camp.code);g=await current();await panel('bag');for(let i=0;i<6;i++)g=await command(g,'salvage',0);await inspect('recycling');await close();await panel('workshop');assert.equal(await page.locator('.p3-craft-preview').count(),15);const before=g.export();await tap(page.locator('[data-recipe="set_weapon_20"] summary'));await inspect('craft preview');if(width===360){fs.mkdirSync('screenshots/p3',{recursive:true});await page.screenshot({path:`screenshots/p3/${engine}-${width}-workshop.png`,fullPage:true});}await tap(page.locator('[data-recipe="set_weapon_20"] summary'));assert.equal((await current()).export(),before,'cancel preview spends nothing');
const oldEquipment=g.equipment().map(x=>x.id);for(const slot of ['weapon','armor','charm']){await close();await panel('workshop');await tap(page.locator(`[data-recipe="set_${slot}_20"] summary`));g=await command(g,'craftGear','set_'+slot+'_20');await inspect('craft result');g=await command(g,'collectLoot','equip');}
assert.equal(g.activeSets().find(x=>x.name==='토끼굴').count,3);await panel('equipment');assert((await page.locator('#bf-panel .p3-set-summary').first().innerText()).includes('토끼굴 · 3/3'));await inspect('set active');await close();await panel('workshop');g=await command(g,'upgrade','weapon');assert((await page.locator('#bf-play').innerText()).includes('강화에 성공했습니다'));await inspect('upgrade feedback');await close();await panel('bag');const oldArmor=g.s.bag.findIndex(x=>x.id===oldEquipment[1]);assert(oldArmor>=0);g=await command(g,'equipBag',oldArmor);assert.equal(g.activeSets().find(x=>x.name==='토끼굴').count,2);await close();await panel('equipment');assert((await page.locator('#bf-panel .p3-set-summary').first().innerText()).includes('토끼굴 · 2/3'));await close();
await panel('workshop');const option=g.tuningOptions('armor')[0];assert(g.canPay(option.cost));await tap(page.locator('.p3-tuning').filter({has:page.locator(`[data-cmd="tuneGear"][data-arg="${option.key}"]`)}).locator('summary'));g=await command(g,'tuneGear',option.key);await inspect('purposeful tuning');await close();const code=g.export();await page.reload();assert.equal((await current()).export(),code,'craft/upgrade/set/tuning survive reconnect');
await restore(fixtures.regions[5].code);g=await current();g=await command(g,'choose',0);g=await command(g,'event',2);const decision=g.s.decisions.p2_margin;assert(decision);await page.reload();assert.equal((await current()).export(),g.export());n=0;while(!(g.p2Reaction()&&(await page.locator('#bf-play').innerText()).includes(g.p2Reaction()))&&n++<100)g=await journeyStep(g);assert(g.p2Reaction());assert((await page.locator('#bf-play').innerText()).includes(g.p2Reaction()));await inspect('remembered regional choice');
for(const choice of [0,1,2]){await restore(fixtures.final.code);g=await current();assert(choice!==2||g.s.mercy>=5);g=await command(g,'finish',choice);assert.equal(await page.locator('.p3-ending-region').count(),3);for(const r of g.endingReport().regions)assert((await page.locator('.p3-ending').innerText()).includes(r.text));assert(!/p2_(bell|water|margin)|set_(weapon|armor|charm)|chapter_\d/.test(await page.locator('.p3-ending').innerText()));await inspect('ending '+choice);const saved=g.export();await page.reload();assert.equal((await current()).export(),saved);}
fs.mkdirSync('screenshots/p3',{recursive:true});await page.screenshot({path:`screenshots/p3/${engine}-${width}-ending.png`,fullPage:true});console.log('PASS P3 UI width '+width+' '+engine);checks.push({width,newGame:true,battle:true,reward:true,shop:true,recycling:true,recipes:15,previewCancel:true,craftReceipts:3,upgrade:true,tuning:true,setActivationAndRemoval:true,exactSave:true,regionalReaction:true,endings:3,errors:errors.length});await context.close();}}finally{await browser.close();}fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+`/ui-${engine}.json`,JSON.stringify({status:'PASS',engine,base,checks,errors:0,fixtureMethod:fixtures.method,limitations:['Responsive widths and touch emulation, not physical devices.','UI path uses real campaign save imports between focused sections; not one uninterrupted campaign.','Firefox uses desktop context with touch events at responsive widths because Playwright Firefox has no isMobile emulation.']},null,2)+'\n');console.log(`PASS P3 ${engine}: 5 widths; new-game battle/reward, shop, recycle, 15 previews, 3 crafts, upgrade/tuning, set swap, save/reload, P2 reaction, 3 endings; zero console/runtime errors`);})().catch(e=>{console.error(e);process.exit(1);});
