(function(){'use strict';
const root=document.getElementById('black-forest-game');document.getElementById('bf-downloads').hidden=!/^https?:$/.test(location.protocol);if(!root||root.dataset.ready)return;root.dataset.ready='1';
const {Game,FAMILY_LABELS,JOBS,AREAS,TYPES,RARITIES,WEIGHTS,AFFIXES,ITEMS,EVENTS,FACTIONS,THREADS,COMPANIONS,NPCS,ASSETS,asset,gearAsset,CHAPTERS,CHAPTER_DECISIONS}=BlackForest;
const $=id=>root.querySelector('#bf-'+id),KEY='black-forest-last-ember-v2',LEGACY='black-forest-last-ember-v1';let game=new Game(),panel='',warning='',panelOrigin='';const hiddenCount=Object.values(JOBS).filter(j=>j.hidden).length;const views={jobs:{query:'',family:'',page:0},codex:{query:'',slot:'',grade:'',found:false,page:0}};
const visibleText=t=>String(t).replace(/보상 받고 다음 조우|다음 조우|계속 진행|자동 이동 중…/g,'계속 나아간다').replace(/보상 수령/g,'전리품을 챙긴다').replace(/체크포인트/g,'쉼터').replace(/경로 선택/g,'길을 살핀다').replace(/랜덤 인카운트/g,'길 위의 사건').replace(/다음 지역/g,'새로운 땅');
const esc=t=>visibleText(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=(label,cmd,arg='',sub='',disabled=false,cls='')=>`<button type="button" class="cursor-interaction ${cls}" data-cmd="${cmd}" data-arg="${esc(arg)}" ${disabled?'disabled':''}>${esc(label)}${sub?`<span>${esc(sub)}</span>`:''}</button>`;
const menu=(label,type,cls='')=>`<button class="cursor-interaction ${cls}" type="button" data-ui="${type}">${label}</button>`;
const meter=(label,n,max)=>`<div><div class="statline"><span>${esc(label)}</span><span>${n} / ${max}</span></div><progress aria-label="${esc(label)}" value="${Math.max(0,n)}" max="${max}"></progress></div>`;
const art=(category,id,label,cls='scene-art')=>{const src=asset(category,id);return `<figure class="${cls}">${src?`<img src="${esc(src)}" alt="${esc(label)}" loading="lazy" decoding="async" width="400" height="600">`:''}<figcaption class="art-fallback" ${src?'hidden':''}>${esc(label)} · 기록의 여백</figcaption></figure>`;};
const portrait=id=>art('classes',id,JOBS[id].name,'class-art');
const conversationScenes=new Set(['dialogue','npc','bond']);
const NOVEL_COPY={
 dialogue:{
  alice:[
   ['앨리스가 가장자리가 탄 증언서를 내민다.','“법정은 매일 누군가의 기억을 증거와 함께 태워.”','멀리서 여왕의 전령이 외친다.','“기억을 남기면 세계가 다시 찢어진다.”'],
   ['증언의 마지막 장에는 세계가 책의 결말을 먹으며 버틴다는 기록이 남아 있다.','앨리스가 낮게 묻는다.','“이걸 누가 가져야 한다고 생각해?”']
  ],
  adam:[
   ['피조물이 낡은 번호표를 뜯어 손바닥에 올린다.','“괴물도 실험체도 아닌 이름을 갖고 싶다.”','빅터가 굳은 얼굴로 심장 장치를 가리킨다.','“저 심장이 멈추면 균열을 막을 방법도 사라진다.”'],
   ['장치를 멈추면 균열 하나를 닫을 수 있다. 대신 피조물의 심장도 함께 멈춘다.','피조물이 당신을 똑바로 바라본다.','“내 삶을 재료로 쓸 거라면, 적어도 내게 먼저 물어라.”']
  ],
  ahab:[
   ['모래 아래로 거대한 흰 그림자가 헤엄친다.','에이해브가 작살을 겨눈다.','“이번엔 놓치지 않는다.”','돈키호테가 그 앞을 막아선다.','“저건 괴물이 아니라 상처 입은 거인일지도 모르오.”'],
   ['백경의 피부에는 사라진 세계들의 마지막 문장이 흉터처럼 새겨져 있다.','에이해브가 작살 끝을 내린다.','“죽이면 길이 열린다. 살리면 기억이 남겠지. 둘 다 가질 순 없다.”']
  ]
 },
 npc:{
  alice:['앨리스가 접힌 증언서를 내민다.','“이름이 지워지기 전에, 네가 먼저 읽어줘.”'],
  queen:['하트 여왕은 판결문에서 시선을 떼지 않는다.','“질서가 사람을 삼키기 시작했다면, 무엇을 고쳐야 하지?”'],
  creature:['피조물이 가슴의 봉합선을 손끝으로 짚는다.','“만들어진 이름 말고, 내가 고른 이름으로 불리고 싶다.”'],
  victor:['빅터가 실험 기록을 덮는다.','“다시 시작할 자격이 있다면… 책임부터 져야겠지.”'],
  ahab:['에이해브가 작살을 바닥에 세운다.','“사냥을 끝낸 뒤에도 내가 남을지는 모르겠군.”'],
  quixote:['돈키호테가 낡은 방패를 고쳐 쥔다.','“세상이 비웃어도, 누군가의 방패가 되는 꿈까지 버릴 순 없지.”']
 },
 bond:{
  alice:[
   ['앨리스가 불탄 명부를 무릎 위에 펼친다.','“내 이름만 남긴다고 끝나는 게 아니야. 사라진 사람들 이름도 되찾고 싶어.”','그녀가 빈칸을 손끝으로 짚는다.','“같이 찾아줄래?”'],
   ['사본의 빈칸에서 희미한 목소리가 새어 나온다.','앨리스가 펜을 당신에게 건넨다.','“여기 적힌 이름들을 세상에 돌려줄지, 이제 같이 결정하자.”']
  ],
  adam:[
   ['피조물이 가슴에 새겨진 창조주의 번호를 보여준다.','“이 번호로 불리고 싶지 않다.”','그가 심장 쪽을 가리킨다.','“내가 고른 이름으로 살아갈 수 있게 도와줄 수 있나?”'],
   ['새 심장틀이 완성되자 빅터가 소유권을 주장한다.','피조물은 떨리는 손으로 펜을 집는다.','“이번에는 내 이름을 내가 쓰겠다.”']
  ],
  ahab:[
   ['에이해브가 부러진 배의 승선 명단을 구겨 쥔다.','“백경만 보느라 돌아갈 사람들을 놓쳤군.”','그가 처음으로 작살 대신 구명정을 바라본다.','“아직 늦지 않았다면, 배부터 고치자.”'],
   ['선원들은 귀환을 원하지만 멀리서 백경의 흔적이 다시 나타난다.','에이해브가 작살을 천천히 내려놓는다.','“이번엔 내가 아니라 네가 정해라. 쫓을지, 돌아갈지.”']
  ]
 }
};
const DIALOGUE_CHOICES={
 alice:[
  ['증언서를 숨겨 앨리스를 보호한다','여왕에게 공개 재판을 요구한다','흰 토끼의 탈출로를 뒤쫓는다','앨리스와 함께 증언의 원본을 확인한다'],
  ['기록을 사람들에게 나눠 준다','법정 기록고에 봉인한다','추적단에 표적의 위치를 넘긴다','앨리스와 사본을 만들어 함께 공개한다']
 ],
 adam:[
  ['피조물에게 자기 이름을 고르게 한다','빅터의 실험 기록부터 검증한다','심장의 근원을 함께 추적한다','피조물과 대체 심장 설계도를 확인한다'],
  ['사람들의 불씨로 심장을 대신한다','피조물의 동의를 받고 실험한다','장치를 부수고 균열로 들어간다','마지막 선택을 피조물에게 맡긴다']
 ],
 ahab:[
  ['돈키호테와 백경의 상처를 살핀다','법정 허가를 받아 포획한다','에이해브와 마지막 항해를 맹세한다','선원들의 퇴로부터 확보한다'],
  ['백경을 풀어주고 문장을 필사한다','기억을 보존한 채 백경을 봉인한다','작살로 세계를 묶은 사슬을 끊는다','선원들을 먼저 귀환시킨다']
 ]
};
const conversationSpeaker=s=>s.scene==='npc'?(NPCS[s.thread]?.name||'낯선 인물'):(COMPANIONS[s.thread]?.name||'동행자');
function conversationLines(s){
 if(s.scene==='dialogue')return NOVEL_COPY.dialogue[s.thread]?.[s.threads[s.thread]]||String(s.message||'').split(/\n+/);
 if(s.scene==='npc')return NOVEL_COPY.npc[s.thread]||String(s.message||'').split(/\n+/);
 if(s.scene==='bond')return NOVEL_COPY.bond[s.thread]?.[s.bondQuests[s.thread]]||String(s.message||'').split(/\n+/);
 return String(s.message||'').split(/\n+/);
}
function conversationCopy(s){
 const speaker=conversationSpeaker(s),relation=s.scene==='npc'?game.affinityTier(s.thread):game.affectionLabel(s.thread);
 return `<section class="conversation-copy" aria-live="polite" aria-label="${esc(speaker)}와의 대화"><header class="conversation-head"><strong>${esc(speaker)}</strong><span>${esc(relation)}</span></header>${conversationLines(s).map(line=>String(line).trim()).filter(Boolean).map(line=>line.startsWith('“')&&line.endsWith('”')?`<blockquote class="conversation-quote">${esc(line)}</blockquote>`:`<p class="conversation-narration">${esc(line)}</p>`).join('')}</section>`;
}
function sceneArt(s){const scene=(category,id,label)=>asset(category,id)?art(category,id,label):art('areas',s.area,label+' · '+AREAS[s.area].name);
 if(['reward','loot','dead'].includes(s.scene)&&s.resultVisual)return scene(s.resultVisual.category,s.resultVisual.id,s.resultVisual.label);
 if(s.scene==='battle')return scene(s.enemy.midboss?'enemies':s.enemy.boss?'bosses':'enemies',s.enemy.name.replace(/^정예\s+/,''),s.enemy.name);
 if(s.scene==='event')return scene('events',s.eventId,EVENTS[s.eventId].title);
 if(['dialogue','bond'].includes(s.scene))return scene('story',s.thread,COMPANIONS[s.thread].name);
 if(s.scene==='npc')return scene(asset('npcs',s.thread)?'npcs':'story',s.thread,NPCS[s.thread].name);
 if(['map','reward','midboss','dead'].includes(s.scene))return art('areas',s.area,AREAS[s.area].name);
 if(s.scene==='camp')return art('misc','camp','불씨의 안식처');
 if(s.scene==='chapter')return scene('story',CHAPTERS[s.area].npc,AREAS[s.area].name+'의 기억');return '';}


const heroScenes=new Set(['map','midboss','battle','dialogue','npc','bond','reward','loot','dead','event','chapter']);
function heroNarrative(s){
 const lines=conversationScenes.has(s.scene)?conversationLines(s):String(s.message||'').split(/\n+/);
 return lines.map(line=>String(line).trim()).filter(Boolean).map(line=>line.startsWith('“')&&line.endsWith('”')?`<blockquote class="scene-hero-quote">${esc(line)}</blockquote>`:`<p class="scene-hero-text">${esc(line)}</p>`).join('');
}
function sceneHero(s,kicker,title){
 const visual=sceneArt(s);
 if(!visual)return '';
 const decision=s.scene==='chapter'?CHAPTER_DECISIONS[s.area]?.[s.chapterSector]:null;
 return `<section class="scene-hero scene-${s.scene}">${visual}<div class="scene-hero-shade" aria-hidden="true"></div><header class="scene-hero-head"><p class="eyebrow">${esc(kicker)}</p><h2>${esc(title)}</h2></header><div class="scene-hero-body" aria-live="polite">${heroNarrative(s)}${decision?`<div class="scene-hero-question"><span>지금 결정할 것</span><strong>${esc(decision.question)}</strong><small>무엇을 지키고 무엇을 감수할지 선택한다.</small></div>`:''}</div></section>`;
}
root.addEventListener('error',ev=>{if(ev.target.tagName==='IMG'){ev.target.hidden=true;const caption=ev.target.parentElement.querySelector('.art-fallback');if(caption)caption.hidden=false;}},true);
window.addEventListener('pageshow',ev=>{if(!ev.persisted)return;try{const code=localStorage.getItem(KEY);if(code)game=Game.load(code);render();}catch(e){warning='남긴 모험 기록을 다시 확인해 주세요.';}});
const overlay=document.createElement('div');overlay.className='modal-overlay';overlay.hidden=true;overlay.setAttribute('aria-hidden','true');root.append(overlay);overlay.addEventListener('click',()=>closePanel());let scrollBefore=0,oldBodyStyle=null;
function lockPanel(){if(oldBodyStyle)return;scrollBefore=window.scrollY;oldBodyStyle={position:document.body.style.position,top:document.body.style.top,width:document.body.style.width,overflow:document.body.style.overflow,boxSizing:document.body.style.boxSizing};Object.assign(document.body.style,{position:'fixed',top:-scrollBefore+'px',width:'100%',overflow:'hidden',boxSizing:'border-box'});overlay.hidden=false;for(const child of root.children)if(child!==overlay&&child!==$('panel'))child.inert=true;}
function unlockPanel(){if(!oldBodyStyle)return;Object.assign(document.body.style,oldBodyStyle);oldBodyStyle=null;overlay.hidden=true;for(const child of root.children)child.inert=false;window.scrollTo(0,scrollBefore);}
const gearName=d=>`${d.name}${d.plus?' +'+d.plus:''}`;
const slotLabel={weapon:'무기',armor:'갑옷',charm:'장신구'};
const labels={gold:'G',ore:'광석',wood:'목재',herb:'약초',hp:'HP',potions:'물약',mercy:'자비',heal:'HP 회복',mana:'MP 회복',xp:'EXP',sigils:'각성 인장',secrets:'비밀 발견',caches:'보급함',crafts:'제작'};
const resources=o=>Object.entries(o).map(([k,v])=>k==='gear'?'장비':`${labels[k]||k} ${v}`).join(' · ')||'없음';
const affixText=d=>d.affixes.map(a=>`${AFFIXES.find(x=>x.id===a.id).label} +${a.value}`).join(' / ')||'추가 옵션 없음';
const gearInfo=d=>`${slotLabel[d.slot]} · ${d.slot==='weapon'?'공격':d.slot==='armor'?'방어':'행운 %'} +${d.power+d.plus*(d.slot==='weapon'?2:1)}`;
const affixSymbols={attack:'⚔',defense:'◇',health:'♥',critical:'✧',dodge:'↗',leech:'◉',poison:'♧',burn:'♨',stun:'ϟ',thorns:'✶',mana:'☽',luck:'♜'};
let gearSelection={slot:'weapon',index:null};
const differences=d=>Object.entries(game.compareGear(d)).filter(([,v])=>v!==0).map(([k,v])=>`${k} ${v>0?'+':''}${v}${['CRIT','DODGE','LEECH','LUCK'].includes(k)?'%':''}`).join(' · ')||'현재 장비와 주요 능력치 동일';
const gearIcon=d=>`<img class="gear-icon" src="${esc(gearAsset(d))}" width="64" height="64" alt="${slotLabel[d.slot]} 공용 아이콘" loading="lazy" decoding="async">`;
let armoryPulse='';
const armoryRarity=d=>d.grade>=4?'legend':d.grade>=3?'epic':d.grade>=2?'rare':'common';
const armoryIcon=d=>`<span class="armory-icon"><span aria-hidden="true">${{weapon:'⚔',armor:'◇',charm:'✧'}[d.slot]}</span>${gearIcon(d)}</span>`;
function equipmentPanel(){
 const s=game.s,j=JOBS[s.job],d=gearSelection.index===null?s[gearSelection.slot]:s.bag[gearSelection.index];
 if(!d){gearSelection={slot:'weapon',index:null};return equipmentPanel();}
 const equipped=gearSelection.index===null;
 return `<div class="armory"><section class="armory-hub" aria-label="현재 직업과 장착 장비"><figure class="armory-portrait">${portrait(s.job)}<figcaption>${esc(j.name)}<span>Lv.${s.level} · ${j.hidden?'Hidden':'Tier '+j.tier} · 공격 ${game.atk()} / 방어 ${game.def()}</span></figcaption></figure><div class="armory-slots">${game.equipment().map(item=>`<button type="button" class="gear-slot rarity-${armoryRarity(item)} ${armoryPulse===item.slot?'gear-equipped':''}" data-ui="gear-slot-${item.slot}" aria-pressed="${equipped&&d.slot===item.slot}" aria-label="${slotLabel[item.slot]}: ${esc(gearName(item))}, ${RARITIES[item.grade]}">${armoryIcon(item)}<span><strong>${slotLabel[item.slot]} · ${esc(gearName(item))}</strong><small>${RARITIES[item.grade]} · ${esc(gearInfo(item))}</small></span></button>`).join('')}</div></section>
 <section class="armory-sheet" tabindex="0" aria-label="장비 비교와 보관 목록"><h3>${equipped?'장착 중':'비교 중'} · ${esc(gearName(d))}</h3>${gearCard(d)}${!equipped?`<p class="comparison" role="status">장착 시: ${esc(differences(d))}</p>`:''}
 <div class="actions">${equipped?b('강화','upgrade',d.slot,`+${d.plus}/8 · ${20*(d.plus+1)}G / 광석 ${3*(d.plus+1)} · ${Math.round(game.upgradeChance(d.slot)*100)}%`,d.plus>=8||s.gold<20*(d.plus+1)||s.ore<3*(d.plus+1))+b('옵션 재설정','reforge',d.slot,'40G / 광석 4',!d.affixes.length||s.gold<40||s.ore<4):b('착용','equipBag',gearSelection.index,'',false,'primary')+b('판매 '+game.price(d)+'G','sellBag',gearSelection.index)+b('분해','salvage',gearSelection.index,'광석 '+(2+d.grade))}</div>
 <details><summary>능력치와 강화 정보</summary><dl class="statgrid">${Object.entries(game.statSnapshot()).map(([k,v])=>`<div><dt>${k}</dt><dd>${Number(v.toFixed(1))}${['CRIT','DODGE','LEECH','LUCK'].includes(k)?'%':''}</dd></div>`).join('')}</dl><p>강화 실패 시 장비·강화 수치 유지 · 연속 실패 ${d.fails}/2</p>${s.legacyEquipment?.length?`<p>이전 확장 슬롯 장비 ${s.legacyEquipment.length}개 보존 · 능력치에는 3슬롯만 반영</p>`:''}</details>
 <h3>보관 장비 ${s.bag.length}/40</h3>${s.bag.map((item,i)=>`<article class="armory-bag-item rarity-${armoryRarity(item)}"><header>${armoryIcon(item)}<div><strong>${esc(gearName(item))}</strong><small>${slotLabel[item.slot]} · ${RARITIES[item.grade]}</small></div></header><p>${esc(differences(item))}</p><div class="actions">${b('착용','equipBag',i,'',false,'primary')}${menu('비교 / 관리','gear-bag-'+i)}</div></article>`).join('')||'<p class="empty">보관 장비가 없습니다. 탐험에서 얻은 장비가 여기에 표시됩니다.</p>'}</section></div>`;
}

function gearFeedback(before){const after=game.statSnapshot(),changes=Object.keys(before).filter(k=>Math.abs(after[k]-before[k])>.001).map(k=>`${k} ${after[k]>before[k]?'+':''}${Number((after[k]-before[k]).toFixed(1))}${['CRIT','DODGE','LEECH','LUCK'].includes(k)?'%':''}`);let toast=$('gear-feedback');if(!toast){toast=document.createElement('div');toast.id='bf-gear-feedback';toast.className='gear-feedback';toast.setAttribute('role','status');root.append(toast);}toast.textContent=game.s.message.split('\n')[0]+(changes.length?' · '+changes.join(' · '):'');toast.hidden=false;clearTimeout(gearFeedback.timer);gearFeedback.timer=setTimeout(()=>{toast.hidden=true;},900);}
const gearCard=d=>`<div class="gear grade-${d.grade}">${gearIcon(d)}<p><span class="rarity">${RARITIES[d.grade]}</span> ${esc(gearName(d))}</p><p class="muted">${gearInfo(d)}</p><p class="muted">${affixText(d)}</p>${d.flavor?`<p class="muted flavor">${esc(d.flavor)}</p>`:''}</div>`;
try{const saved=localStorage.getItem(KEY)||localStorage.getItem(LEGACY);if(saved)game=Game.load(saved)}catch(e){warning='자동 저장을 읽지 못했습니다. 저장 코드를 불러오거나 새 모험을 시작하세요.'}
function save(){try{if(game.migrationSource){localStorage.setItem(KEY+'.before-v4',game.migrationSource);delete game.migrationSource;}localStorage.setItem(KEY,game.export());$('save-status').textContent='자동 저장됨 · 통합판 4.0'}catch(e){$('save-status').textContent='자동 저장 불가 · 저장 코드를 복사해 보관하세요.'}}
const pct=n=>(n*100).toFixed(0)+'%';
function statusDetails(){const st=game.combatStatus(),j=JOBS[game.s.job];return `<h3>상세 스테이터스</h3><dl class="statgrid">${[['공격력',game.atk()],['방어력',game.def()],['치명타율',pct(st.crit)],['치명타 배율','170%'],['회피율',pct(st.dodge)],['행운',pct(st.luck)],['기본 흡혈',pct(st.leech)],['피해 반사',st.reflect],['일반 공격 방어 관통',st.pierce],['스킬 MP 소모',st.skillCost],['방어 피해 감소','70%']].map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><p class="muted">흡혈은 직업별 스킬에서 추가될 수 있습니다. 행운은 장비 드롭과 등급 가중치에 적용됩니다.</p><div class="item"><p>${esc(j.skill)} · MP ${st.skillCost} · 숙련도 ${st.mastery}</p><p>${esc(j.passive||j.desc)}</p></div><h3>현재 전투 효과</h3><p>${esc(st.statuses.map(x=>({poison:'중독',burn:'화상',bleed:'출혈',damageOverTime:'지속 피해',stun:'기절',atkDown:'공격 약화',guard:'방어 후 집중'}[x.id]||x.id)+' · '+x.duration+'턴 · '+x.value).join(' / ')||'적용 중인 일시 효과 없음')}</p><h3>동료 지원</h3><p>${game.allies().map(id=>esc(COMPANIONS[id].aid)).join(' · ')||'개인 퀘스트 완료 + 호감도 80 이상에서 보스전 지원'}</p>`}
function render(){const s=game.s;root.dataset.scene=s.scene;const job=JOBS[s.job];const opening=s.scene==='camp'&&s.cleared.length===0&&s.turns===0&&String(s.message||'').startsWith('프롤로그 — 마지막 불씨');$('stats').innerHTML=job?`<div class="stats">${meter('HP',s.hp,game.maxHp())}${meter('MP',s.mp,game.maxMp())}${meter('Lv.'+s.level+' '+job.name,s.xp,game.need())}<div><div class="statline"><span>골드</span><span>${s.gold} G</span></div><p class="muted">공격 ${game.atk()} · 방어 ${game.def()}</p>${menu('상세 스테이터스','status','small')}</div></div>`:'';
if(!job){$('play').innerHTML=`${art('misc','banner','검은 숲으로 향하는 방랑자')}<p class="eyebrow">CAREER / 첫 불씨의 선택</p><div class="story">${esc(s.message)}\n\n8개 지역 · 일반 ${Object.keys(JOBS).length-hiddenCount}개 + 히든 ${hiddenCount}개 직업 · ${ITEMS.length}종의 장비 · 고전 문학이 뒤섞인 도서계\n당신의 싸움은 어떤 모습인가?</div><div class="classcards">${s.offers.map(id=>[id,JOBS[id]]).map(([id,j])=>`<button class="cursor-interaction" type="button" data-cmd="start" data-arg="${id}">${portrait(id)}<b>${j.name}</b><p>${j.desc}</p><p class="muted">HP ${j.hp} · MP ${j.mp} · 공격 ${j.atk}</p></button>`).join('')}</div><p class="muted">히든 직업 해금 ${s.unlocked.length}/${hiddenCount} · 수집한 장비 ${s.collection.length}/${ITEMS.length}</p>`;return}
let title='',kicker='',actions='',extra='';
if(s.scene==='chapter'){const decision=CHAPTER_DECISIONS[s.area][s.chapterSector],record='chapter_'+s.area+'_'+s.chapterSector;title=AREAS[s.area].name+' · '+['외곽','심부','중심부'][s.chapterSector];kicker='CHAPTER / 선택의 기록';extra='';actions=s.decisions[record]?b('남긴 기록을 다시 읽는다','chapterChoice',0,'이전 선택 유지'):decision.choices.map((c,i)=>b(c.label,'chapterChoice',i,c.result)).join('');}
if(s.scene==='camp'){title=opening?'검은 숲에 눈을 뜨다':'방랑자의 캠프';kicker=opening?'PROLOGUE / 마지막 불씨':'SANCTUARY / 불씨가 머무는 곳';actions=AREAS.map((a,i)=>b(a.name,'enterArea',i,i>s.cleared.length?'이전 지역의 인장 필요':s.cleared.includes(i)?'정복 완료 · 재탐험':'외곽 → 심부 → 중심부 · 12노드',i>s.cleared.length,i===s.cleared.length?'primary':'')).join('')+b(`별 없는 회랑 ${s.rift+1}층`,'enterArea',8,'비밀 발견 1회 또는 보스 4명 처치 후 개방',s.secrets<1&&s.cleared.length<4,'wide');if(s.checkpoint)actions=b('길을 이어간다','resumeJourney','','노드 '+s.checkpoint.step+'/12',false,'primary')+b('돌아갈 길을 택한다','abandonChapter','','다른 지역으로 이동하려면 선택');extra=`<div class="campnav">${b('휴식 · 무료','rest','','HP·MP 완전 회복')}${b('물약 · 16G','buy','potion','',s.gold<16)}${menu('제작 / 강화','workshop')}${menu('장비 / 비교','equipment')}${menu('장비 가방','bag')}${menu('직업 비전서','jobs')}${menu('의뢰 게시판','quests')}${menu('인물 / 메인 퀘스트','story')}</div>`}
if(s.scene==='map'){title=s.kind==='rift'?`별 없는 회랑 ${s.rift+1}층`:AREAS[s.area].name;const bossNext=s.routes[0]==='boss';kicker='JOURNEY / '+(s.kind==='rift'?'회랑':game.sector())+' · 길을 나서다';extra=`<div class="route" aria-label="탐험 ${s.step}/${game.limit()}">${Array.from({length:game.limit()+1},(_,i)=>`<span class="step ${i<s.step?'done':''} ${i===s.step?'current':''}">${i===game.limit()?'왕':i+1}</span>`).join('')}</div><p class="muted encounter-hint">${bossNext?'마지막 문 앞이다. 수문장이 기다리고 있다.':'낯선 흔적이 앞쪽으로 이어진다.'}</p>`;actions=b(bossNext?(s.kind==='rift'?'문 너머로 나아간다':'문 너머로 나아간다'):'계속 나아간다','choose',0,bossNext?'보스 전투 · 장비와 각성 인장 확정':'눈앞의 흔적을 따라 길을 나선다',false,'primary wide')+b('캠프로 귀환','retreat','','현재 탐험을 포기하고 입구부터 다시 시작',false,'wide')}
if(s.scene==='battle'){const e=s.enemy;title=e.name;kicker=e.boss?'BOSS / 인장의 수호자':e.elite?'ELITE / 위험한 조우':'BATTLE / 맞서 싸우다';extra=`<div class="enemy">${meter(e.name,e.hp,e.maxHp)}<p class="intent">다음 행동: ${{attack:'공격 · 예상 피해 '+game.damagePreview(),heavy:'강공격 · 예상 피해 '+game.damagePreview()+' / 방어 권장',guard:'방어 · 물리 피해 절반',charge:'힘 모으기 · 공격 없음',heal:'회복 · 최대 HP의 10%'}[e.intent]}</p>${e.dotTurns?`<p class="muted">지속 피해 ${e.dot} · ${e.dotTurns}턴</p>`:''}</div>`;actions=b('일반 공격','act','attack','MP +1',false,'primary')+b(job.skill,'act','skill',`MP ${game.skillCost()} · `+job.desc,s.mp<game.skillCost())+b('방어 / 집중','act','defend','피해 70% 감소 · MP +3')+b(`회복 물약 (${s.potions})`,'act','potion','HP 55% 회복 · 적 행동 진행',s.potions<1||s.hp===game.maxHp())+b('도주','act','flee',e.boss?'보스에게서는 도주 불가':'성공 확률 75%',e.boss,'wide')}
if(s.scene==='dialogue'){const t=THREADS[s.thread],stage=s.threads[s.thread],labels=DIALOGUE_CHOICES[s.thread]?.[stage];title=t.name;kicker='DIALOGUE / '+COMPANIONS[s.thread].name;extra=meter('호감도 · '+game.affectionLabel(s.thread),s.affection[s.thread],100);actions=game.dialogueOptions().map((c,i)=>b(labels?.[i]||c.label,'dialogue',i,`${c.required?'호감도 '+c.required+' 필요 · ':''}호감도 ${c.delta>=0?'+':''}${c.delta}`,s.affection[s.thread]<c.required)).join('')}
if(s.scene==='npc'){title=NPCS[s.thread].name;kicker='DIALOGUE / 개인 대화';extra=meter('호감도 · '+game.affinityTier(s.thread),game.getAffinity(s.thread),100);actions=['네 뜻을 먼저 듣겠다','내 판단대로 따르라고 한다','거리를 두고 상황을 기록한다','같이 조사하자'].map((label,i)=>b(label,'npcChoice',i,i===3?'호감도 40 필요 · 인장 +1 · 20G':'호감도 '+[12,-10,4][i],i===3&&game.getAffinity(s.thread)<40)).join('');}
if(s.scene==='bond'){const c=COMPANIONS[s.thread],stage=s.bondQuests[s.thread];title=c.quest;kicker='BOND / '+c.name;extra=meter('호감도 · '+game.affectionLabel(s.thread),s.affection[s.thread],100);actions=b(c.tasks[stage],'bondChoice',0,'비용: '+resources(c.costs[stage])+' · 호감도 +10',!game.canPay(c.costs[stage]),'primary')+b('부탁을 저버리고 이익을 챙긴다','bondChoice',1,'25G · 호감도 −25 · 개인 퀘스트 종료')+b('나중에 결정한다','bondChoice',2,'진행과 호감도 유지')}
if(s.scene==='reward'){const checkpoint=s.kind==='story'&&[4,8,12].includes(s.step),r=s.rewardState,pending=r&&!r.claimed;
 title=pending?'싸움이 끝난 자리':checkpoint?'바람을 피할 작은 공터':'잠깐의 고요';kicker='JOURNEY / 길 위의 기록';
 extra=pending?`<section class="reward-summary" aria-label="챙길 전리품"><p>경험치 +${r.rewards.xp} · 골드 +${r.rewards.gold}</p><p>목재 +${r.rewards.wood} · 약초 +${r.rewards.herb} · 광석 +${r.rewards.ore}${r.rewards.sigils?' · 각성 인장 +'+r.rewards.sigils:''}</p></section>`:'';
 const label=pending?(r.destination==='reward'?'전리품을 챙기고 나아간다':r.destination==='final'?'인장을 챙긴다':'전리품을 챙기고 캠프로 돌아간다'):s.resultKind==='npc'?'작별하고 길을 나선다':s.resultKind==='shrine'?'성소를 뒤로한다':s.resultKind==='secret'?'비밀을 뒤로하고 나아간다':s.resultKind==='cache'?'쓸 만한 물건을 챙기고 나아간다':'계속 나아간다';
 actions=b(label,'nextEncounter','','',false,'primary wide')+(checkpoint&&!pending?b('잠시 쉬어간다','pauseChapter','','여기까지의 여정이 기록됩니다.'):'');}
if(s.scene==='midboss'){title='샛길과 발소리';kicker='JOURNEY / 기둥 너머';actions=b('수문장과 마주한다','faceMidboss','','',false,'primary')+b('샛길로 몸을 숨긴다','skipMidboss');}
if(s.scene==='merchant'){title='떠돌이 상인';kicker='TRADER / 확률을 파는 가게';actions=b('회복 물약을 산다 · 16G','buy','potion','',s.gold<16)+b('맑은 영약을 산다 · 12G','buy','tonic','MP 완전 회복',s.gold<12||s.mp===game.maxMp())+b('봉인된 장비를 산다 · 55G','buy','gear','정예 장비 확률표 적용',s.gold<55)+b('상점을 떠난다','nextEncounter','','다시 길을 나선다',false,'primary')}
if(s.scene==='event'){const ev=EVENTS[s.eventId];title=ev.title;kicker='STORY / 선택과 대가';actions=ev.choices.map((c,i)=>b(c.label,'event',i,`비용: ${resources(c.cost)} · 성공 ${Math.round(c.chance*100)}% · 성공 보상 ${resources(c.reward)}`,!game.canPay(c.cost))).join('');extra=''}
if(s.scene==='loot'){const d=s.loot;title=gearName(d);kicker='DISCOVERY / 운명이 남긴 물건';extra=(s.rewardState&&!s.rewardState.claimed?`<p class="reward-summary">경험치 +${s.rewardState.rewards.xp} · 골드 +${s.rewardState.rewards.gold} · 목재 +3 · 약초 +2 · 광석 +${s.rewardState.rewards.ore}</p>`:'')+gearCard(d)+`<p class="comparison">장착 시: ${esc(differences(d))}</p><p class="muted compare">현재 장비</p>`+gearCard(s[d.slot]);actions=b('장비를 걸치고 나아간다','collectLoot','equip','기존 장비는 가방으로',false,'primary')+b('장비를 챙기고 나아간다','collectLoot','bag','캠프에서 장착 가능')+b(`판매 · ${game.price(d)}G`,'collectLoot','sell','',false,'wide')}
if(s.scene==='dead'){title='아직 꺼지지 않은 불씨';kicker='FALLEN / 다시 일어서는 자';actions=b('상처를 추스르고 일어난다','revive','','골드 20% 손실 · 장비·직업 유지',false,'primary wide')}
if(s.scene==='final'){title='첫 불씨의 기억';kicker='EPILOGUE / 마지막 선택';actions=b('불씨를 놓아준다','finish',0,'저주를 끝내고 기억을 보내 준다')+b('왕관을 쓴다','finish',1,'왕의 힘과 책임을 이어받는다')+b('불씨를 모두에게 나눈다','finish',2,`자비 5 필요 · 현재 ${s.mercy}`,s.mercy<5,'wide primary')}
if(s.scene==='ending'){title=s.ending;kicker='THE END / 새벽 너머';extra=`<div class="row"><span class="badge">Lv.${s.level} ${job.name}</span><span class="badge">처치 ${s.kills}</span><span class="badge">수집 ${s.collection.length}/${ITEMS.length}</span></div>`;actions=b('불씨를 품고 캠프로 돌아간다','postgame','','회랑·장비·직업 수집',false,'primary')+menu('다음 여정을 시작한다','restart')}
const side=`<aside><details class="sideblock equipment-details"><summary>장착 장비 · ${esc(s.weapon.name)}</summary>${game.equipment().map(d=>`<div class="item">${gearCard(d)}</div>`).join('')}</details><div class="sideblock"><p class="eyebrow">SUPPLIES</p><p>물약 ${s.potions} · 각성 인장 ${s.sigils}</p><p class="muted">목재 ${s.wood} · 광석 ${s.ore} · 약초 ${s.herb}</p><p class="muted">캠프 Lv.${s.camp} · 자비 ${s.mercy}</p></div><div class="sideblock"><p class="eyebrow">DESTINY</p><p>지역 ${s.cleared.length}/8 · 비전 ${s.unlocked.length}/${hiddenCount}</p><p class="muted">전설 보정 ${s.pity}/29</p><p class="muted">치명타 ${Math.round(game.crit()*100)}% · 회피 ${Math.round(game.dodge()*100)}%</p>${menu('장비 / 비교','equipment','small')}${menu('도감 / 확률표','codex','small')}</div></aside>`;
const hero=heroScenes.has(s.scene)?sceneHero(s,kicker,title):'';
const intro=hero||`<p class="eyebrow">${kicker}</p><h2>${esc(title)}</h2>${sceneArt(s)}${conversationScenes.has(s.scene)?conversationCopy(s):`<div class="story ${opening?'opening-story':''}" aria-live="polite">${esc(s.message)}</div>`}`;
$('play').innerHTML=`<div class="layout ${s.scene==='battle'?'in-battle':''} ${conversationScenes.has(s.scene)?'is-conversation':''}"><main class="main">${intro}${s.scene!=='camp'?extra:''}${actions?`<div class="actions">${actions}</div>`:''}${s.scene==='camp'?extra:''}</main>${side}</div><form id="bf-command-form" class="commandrow"><label for="bf-command">직접 입력</label><input id="bf-command" type="text" maxlength="80" autocomplete="off" placeholder="예: 공격, 방어, 물약, 계속"><button type="submit" class="cursor-interaction">실행</button><p class="muted" id="bf-command-status" role="status">지원 명령: 공격 · 스킬 · 방어 · 물약 · 도주 · 휴식 · 귀환 · 계속 · 1/2/3/4</p></form>`;

}
function showPanel(type){if(panel!==type){panelOrigin=type; if(views[type])views[type].page=0;}panel=type;const el=$('panel'),s=game.s;el.hidden=false;el.classList.toggle('armory-panel',type==='equipment');lockPanel();const close=menu('닫기','close','small');let html='';
if(type==='status')html=statusDetails()+close;
if(type==='save')html=`<h3>저장 / 불러오기</h3><p class="muted">압축된 BF3 저장 코드를 보관해 다른 기기에서 이어 하세요. 이전 버전의 JSON 저장 코드도 읽을 수 있습니다. 불러오기는 현재 진행을 대체합니다.</p><label class="muted" for="bf-code">저장 코드</label><textarea id="bf-code" spellcheck="false"></textarea><div class="row">${menu('복사','copy')}${menu('저장 파일 받기','download')}${menu('코드 불러오기','load','primary')}<label class="file-label">저장 파일 불러오기<input id="bf-save-file" type="file" accept=".bfsave,.txt,.json"></label>${close}</div><p id="bf-code-status" role="status" class="muted"></p>`;
if(type==='restart')html=`<h3>새로운 모험</h3><p class="muted">해금 직업·장비 도감·엔딩 기록은 유지됩니다. 레벨·장비·재화·탐험 진행은 초기화됩니다. 8개 지역 완주 후 새 모험은 적 능력치가 15%씩 증가합니다. 현재 기록은 저장 코드로 별도 보관할 수 있습니다.</p><div class="row">${menu('해금 유지 · 새 모험','confirm-restart','primary')}${close}</div>`;
if(type==='journal')html=`<h3>모험 기록</h3>${s.log.length?s.log.map(t=>`<div class="logitem">${esc(t)}</div>`).join(''):'<p>아직 기록이 없습니다.</p>'}${close}`;
if(type==='jobs')html=`<h3>직업 비전서</h3><p>현재 ${esc(JOBS[s.job].name)} · ${JOBS[s.job].hidden?'Hidden':'Tier '+JOBS[s.job].tier} · 숙련도 ${game.mastery()}</p><p class="muted">이번 모험의 성장: ${s.career.history.map(id=>esc(JOBS[id].name)).join(' → ')}. 다른 계열은 새로운 모험에서 선택합니다.</p><h3>다음 전직 후보</h3>${game.careerCandidates().map(c=>`<div class="item">${portrait(c.id)}<h3>${JOBS[c.id].name}</h3><p>${esc(JOBS[c.id].desc)}</p>${c.progress.map(r=>`<p class="muted">${r.now>=r.need?'✓':'○'} ${esc(r.label)} ${r.now}/${r.need}</p>`).join('')}${b('전직','changeJob',c.id,'',!c.available)}</div>`).join('')||'<p>일반 경로의 마지막 직업입니다. 히든 비전은 아래에서 확인합니다.</p>'}<h3>전체 직업 / 발견 비전</h3><p class="muted">조건 달성 후 각성 인장 1개로 비전을 해금합니다. 인장은 보스·비밀 방에서 확정, 일반 적 8%·정예 15%를 기본으로 드롭합니다.</p>${filterControls('jobs')}<div id="bf-job-list" class="joblist"></div>${pager('jobs')}<p class="muted">현재: 자비 ${s.mercy}, 보스 ${s.cleared.length}, 위기 후 승리 ${s.lowhpWins}, 처치 ${s.kills}, 정예 ${s.elites}, 제작 ${s.crafts}, 보급함 ${s.caches}, 희귀 이상 획득 ${s.rareFinds}, 비밀 ${s.secrets}</p>${close}`;
if(type==='workshop')html=`<h3>제작 / 강화</h3><p class="muted">+5까지 확정. +6/7/8 성공률 80/60/40%. 실패해도 장비·강화 수치 유지, 재료는 소모됩니다. 같은 강화 단계에서 2회 연속 실패하면 다음 시도는 확정입니다.</p><div class="actions">${b('물약 제작','craft','','약초 3',s.herb<3)}${b(s.camp>=8?'캠프 최대 레벨':'캠프 Lv.'+(s.camp+1),'campUp','',`목재 ${8*s.camp} · ${15*s.camp}G`,s.camp>=8||s.wood<8*s.camp||s.gold<15*s.camp)}${game.equipment().map(d=>b(`${slotLabel[d.slot]} +${d.plus>=8?'8 완료':d.plus+1}`,'upgrade',d.slot,`${Math.round(game.upgradeChance(d.slot)*100)}% · ${20*(d.plus+1)}G · 광석 ${3*(d.plus+1)}`,d.plus>=8||s.gold<20*(d.plus+1)||s.ore<3*(d.plus+1))+b(slotLabel[d.slot]+' 옵션 재설정','reforge',d.slot,'마지막 옵션 무작위 변경 · 40G · 광석 4',!d.affixes.length||s.gold<40||s.ore<4)).join('')}</div>${close}`;
if(type==='equipment'){if(gearSelection.index!==null&&!s.bag[gearSelection.index])gearSelection.index=null;html=equipmentPanel()+close;}
if(type==='bag')html=`<h3>장비 가방 ${s.bag.length}/40</h3><p class="muted">가득 차면 가장 오래된 보관 장비를 자동 분해합니다.</p>${s.bag.map((d,i)=>`<div class="item">${gearCard(d)}<div class="row">${menu('상세 / 비교','gear-bag-'+i)}${b('장착','equipBag',i)}${b('판매 '+game.price(d)+'G','sellBag',i)}${b('분해 · 광석 '+(2+d.grade),'salvage',i)}</div></div>`).join('')||'<p class="empty">보관된 장비가 없습니다.</p>'}${close}`;
if(type==='quests')html=`<h3>의뢰 게시판</h3>${game.quests().map(q=>`<div class="item"><p>${q.name} · ${Math.min(q.now,q.max)}/${q.max}</p><p class="muted">${q.text} · 보상 ${q.gold}G + 물약 1</p>${b(s.claims.includes(q.id)?'수령 완료':'보상 받기','claim',q.id,'',s.claims.includes(q.id)||q.now<q.max)}</div>`).join('')}${close}`;
if(type==='story')html=`<h3>세력 평판</h3>${FACTIONS.map(c=>`<div class="item"><h3>${c.name} · ${s.factions[c.id]}</h3><p>${c.benefit}</p></div>`).join('')}<h3>개인 관계</h3>${Object.entries(NPCS).map(([id,c])=>`<div class="item">${art('npcs',id,c.name,'class-art')}<h3>${c.name} · ${game.affinityTier(id)}</h3>${meter('개인 호감도',game.getAffinity(id),100)}${b('대화하기','meetNpc',id,'첫 인장 이후 · 지역 수복마다 한 번',s.cleared.length<1||s.npcVisits[id]===s.cleared.length)}</div>`).join('')}`+`<h3>인물과 인연</h3><p class="muted">선택은 각 인물의 호감도를 바꿉니다. 0–19 경계 · 20–39 중립 · 40–59 호의 · 60–79 신뢰 · 80–100 친밀. 호감도 40에서 공동 해결 선택지, 60에서 개인 퀘스트, 80 + 개인 퀘스트 완료에서 보스전 지원이 열립니다.</p>${Object.entries(COMPANIONS).map(([id,c])=>`<section class="item"><h3>${c.name} · ${game.affectionLabel(id)}</h3>${meter('호감도',s.affection[id],100)}<p>${tText(id)}</p><p class="muted">${Object.entries(s.decisions).filter(([k])=>k.startsWith(id)).map(([,v])=>esc(v)).join(' → ')||'아직 함께한 사건이 없습니다.'}</p><div class="actions">${b(s.threads[id]===2?'메인 사건 해결':'메인 사건을 살핀다','thread',id,THREADS[id].name+' · '+s.threads[id]+'/2 · 첫 지역 인장 필요',s.threads[id]===2||s.cleared.length<1)}${b('모닥불 대화','gift',id,'15G · 호감도 +15 · 지역 인장 수복마다 1회',s.gold<15||s.cleared.length<1||s.bondGifts[id]===s.cleared.length)}${b(s.bondQuests[id]===2?'개인 퀘스트 종료':'개인 퀘스트 '+(s.bondQuests[id]+1)+'/2','bondQuest',id,c.quest+' · 메인 사건 완료 · 호감도 60 · 인장 '+(s.bondQuests[id]===0?2:4)+'개 필요',!game.bondAvailable(id),'wide')}</div><p class="muted">${s.bondOutcome[id]==='broken'?'부탁을 저버려 동료 지원을 얻지 못했습니다.':s.bondOutcome[id]==='saved'?(s.affection[id]>=80?c.aid:'부탁 완료 · 호감도 80에서 지원'):c.aid+' · 개인 퀘스트 완료 필요'}</p></section>`).join('')}${close}`;
if(type==='codex'){const odds=Object.entries(WEIGHTS).map(([id,w])=>`<tr><td>${{normal:'일반',elite:'정예·상인',boss:'보스',secret:'비밀 방'}[id]}</td>${w.map(v=>`<td>${v}%</td>`).join('')}</tr>`).join('');html=`<h3>장비 도감 / 확률표</h3><p class="muted">기본 장비 등급 확률입니다. 행운은 영웅 이상 가중치를 1~2배로 높이고 전체를 다시 정규화합니다. 29회 연속 전설 미만이면 다음 장비는 전설 이상입니다. 현재 ${s.pity}/29.</p><div class="tablewrap"><table><thead><tr><th>획득처</th>${RARITIES.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${odds}</tbody></table></div><p class="muted">장비 등장: 일반 적 55%+행운, 정예·보스 100%. 비밀 방 기본 경로 가중치 5/100; 11회 탐험 동안 발견하지 못하면 비밀 경로가 확정 제시됩니다. 미지의 길에도 비밀 방이 숨어 있습니다. 보급함의 미믹 확률은 10%입니다.</p><h3>발견한 장비 ${s.collection.length}/${ITEMS.length}</h3>${filterControls('codex')}<div id="bf-collection" class="collection"></div>${pager('codex')}<h3>몬스터 기록 ${Object.keys(s.bestiary).length}종</h3><p class="muted">${Object.entries(s.bestiary).map(([n,v])=>`${esc(n)} ${v}회`).join(' · ')||'처치한 몬스터가 없습니다.'}</p>${close}`}
if(type==='credits')html=`<h3>실제 도입한 오픈소스</h3><p><a href="https://github.com/ondras/rot.js" target="_blank" rel="noopener">rot.js 2.2.1</a> — 시드 난수·상태 복원.</p><p><a href="https://github.com/jotson/LootTable.js" target="_blank" rel="noopener">LootTable.js 0.1.0</a> — 장비 등급·갈림길·적 행동 가중치 추첨. 난수 주입을 위한 작은 수정을 적용했습니다.</p><p><a href="https://github.com/pieroxy/lz-string" target="_blank" rel="noopener">lz-string 1.5.0</a> — 저장 코드 압축·복원.</p><p class="muted">직업·무기·몬스터·이야기·게임 규칙은 이 확장판의 자체 콘텐츠입니다. 확률은 게임 내 재화에만 적용됩니다.</p><details><summary>라이선스 전문</summary><pre id="bf-license"></pre></details>${close}`;
el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-label','모험 메뉴');el.tabIndex=-1;el.innerHTML='<div class="panelbar"><span>모험 메뉴</span>'+menu('닫기','close','small')+'</div>'+html.replaceAll(close,'');if(type==='jobs')drawJobs();if(type==='codex')drawCollection();el.focus({preventScroll:true});if(type==='save')$('code').value=game.export();if(type==='credits')$('license').textContent=root.dataset.license||'';
}

function tText(id){return esc(game.relationGreeting(id))}
function closePanel(){$('panel').hidden=true;panel='';unlockPanel();root.querySelector('[data-ui="'+panelOrigin+'"]')?.focus({preventScroll:true});}
function filterControls(type){const v=views[type];return `<div class="filters"><label>검색<input data-filter="${type}:query" type="search" value="${esc(v.query)}" placeholder="직업명·발견한 장비명"></label>${type==='jobs'?`<label>계열<select data-filter="jobs:family"><option value="">전체 계열</option>${Object.entries(FAMILY_LABELS).map(([id,n])=>`<option value="${id}" ${v.family===id?'selected':''}>${n}</option>`).join('')}</select></label>`:`<label>종류<select data-filter="codex:slot"><option value="">전체 종류</option>${Object.entries(slotLabel).map(([id,n])=>`<option value="${id}" ${v.slot===id?'selected':''}>${n}</option>`).join('')}</select></label><label>등급<select data-filter="codex:grade"><option value="">전체 등급</option>${RARITIES.map((n,i)=>`<option value="${i}" ${v.grade===String(i)?'selected':''}>${n}</option>`).join('')}</select></label><label class="check"><input data-filter="codex:found" type="checkbox" ${v.found?'checked':''}>발견한 장비만</label>`}</div>`;}
function pager(key){return `<div class="pager" id="bf-${key}-pager"></div>`;}
function pageSlice(key,list,size){const v=views[key],last=Math.max(0,Math.ceil(list.length/size)-1);v.page=Math.max(0,Math.min(last,v.page));$(key+'-pager').innerHTML=menu('이전','page-'+key+'-prev','small')+`<span role="status">${list.length}개 · ${v.page+1}/${last+1}쪽</span>`+menu('다음','page-'+key+'-next','small');$(key+'-pager').querySelector('button:first-child').disabled=v.page===0;$(key+'-pager').querySelector('button:last-child').disabled=v.page===last;return list.slice(v.page*size,(v.page+1)*size);}
function drawJobs(){const s=game.s,v=views.jobs,list=Object.entries(JOBS).filter(([id,j])=>{const unlocked=!j.hidden||s.unlocked.includes(id),family=j.family||(j.hidden?'hidden':'basic');return (!v.family||v.family===family||v.family==='hidden'&&j.hidden)&&(!v.query||(unlocked?j.name+' '+j.desc:j.hint+' '+j.requirement).includes(v.query));});$('job-list').innerHTML=pageSlice('jobs',list,20).map(([id,j])=>{const unlocked=!j.hidden||s.unlocked.includes(id),eligible=game.eligible(id),available=game.jobAvailable(id);return `<div class="item">${unlocked?portrait(id):''}<h3>${unlocked?j.name:eligible?'발견: '+j.name:'??? · '+j.hint}</h3><p class="muted">${unlocked?(j.tier!==null?'T'+j.tier+' · '+(FAMILY_LABELS[j.family]||'근접')+' · '+j.passive+' — ':'')+j.desc:j.requirement}</p>${unlocked?`<p class="muted">${esc(j.lore||'')}</p><p class="muted">${j.hidden?'정상 계보 밖의 발견형 직업':j.parents.length?'이전 직업: '+j.parents.map(id=>esc(JOBS[id].name)).join(' / '):'시작 직업'}</p>`:''}${unlocked?b(s.job===id?'현재 직업':'전직하기','changeJob',id,j.hidden?'선택하면 일반 전직 경로 종료':game.unlockProgress(id).filter(r=>r.now<r.need).map(r=>r.label+' '+r.now+'/'+r.need).join(' · '),s.job===id||!available):b('비전 해금 · 인장 1','awaken',id,eligible?'조건 충족':'조건 미충족',!eligible||s.sigils<1)}</div>`}).join('')||'<p class="empty">검색 결과가 없습니다.</p>';}
function drawCollection(){const v=views.codex,found=new Set(game.s.collection),list=ITEMS.filter(d=>(!v.slot||d.slot===v.slot)&&(v.grade===''||d.fixedGrade===undefined||d.fixedGrade===Number(v.grade))&&(!v.found||found.has(d.id))&&(!v.query||found.has(d.id)&&(d.name+' '+d.category).includes(v.query)));$('collection').innerHTML=pageSlice('codex',list,48).map(d=>`<div class="collectionitem ${found.has(d.id)?'found':''}">${found.has(d.id)?esc(d.name):'??? · '+slotLabel[d.slot]}<p class="muted">${d.fixedGrade===undefined?'가변 등급':RARITIES[d.fixedGrade]} · ${AREAS[d.minArea||0].name}부터</p>${found.has(d.id)?`<p class="muted">${esc(d.flavor||'')}</p>`:''}</div>`).join('')||'<p class="empty">검색 결과가 없습니다.</p>';}
root.addEventListener('input',ev=>{const key=ev.target.dataset.filter;if(!key)return;const [type,field]=key.split(':');views[type][field]=ev.target.type==='checkbox'?ev.target.checked:ev.target.value;views[type].page=0;type==='jobs'?drawJobs():drawCollection();});
root.addEventListener('change',async ev=>{if(ev.target.id!=='bf-save-file')return;const file=ev.target.files[0];if(!file)return;try{if(file.size>300000)throw Error('oversize');const code=await file.text();const loaded=Game.load(code);game=loaded;render();save();closePanel();}catch(e){$('code-status').textContent='불러오기 실패. 올바른 저장 파일을 선택하세요. 현재 진행은 유지됩니다.';}});
root.addEventListener('keydown',ev=>{if(!panel)return;if(ev.key==='Escape'){ev.preventDefault();closePanel();return}if(ev.key==='Tab'){const nodes=[...$('panel').querySelectorAll('button:not(:disabled),input,select,textarea,a[href],summary,[tabindex="0"]')],first=nodes[0],last=nodes.at(-1);if(ev.shiftKey&&(document.activeElement===first||document.activeElement===$('panel'))){ev.preventDefault();last?.focus()}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first?.focus()}}});
const commands=['start','faceMidboss','skipMidboss','travel','enterArea','choose','act','retreat','advance','nextEncounter','rest','buy','event','takeLoot','collectLoot','revive','finish','postgame','craft','campUp','upgrade','reforge','equipBag','sellBag','salvage','claim','awaken','changeJob','thread','dialogue','gift','bondQuest','bondChoice','meetNpc','npcChoice','chapterChoice','pauseChapter','resumeJourney','abandonChapter'];
let lastJourneyAction=-Infinity;
root.addEventListener('click',ev=>{const target=ev.target.closest('button');if(!target||target.disabled||!root.contains(target)||!target.isConnected)return;const cmd=target.dataset.cmd;if(cmd){if(!commands.includes(cmd))return;const journeyAction=['nextEncounter','collectLoot','enterArea','resumeJourney','faceMidboss','skipMidboss','chapterChoice','event','npcChoice','dialogue','bondChoice'].includes(cmd);if(journeyAction&&(ev.detail>1||performance.now()-lastJourneyAction<250))return;if(journeyAction)lastJourneyAction=performance.now();target.disabled=true;const arg=target.dataset.arg,numeric=['enterArea','travel','choose','event','finish','equipBag','sellBag','salvage','dialogue','bondChoice','npcChoice','chapterChoice'];const armoryScroll=$('panel').querySelector('.armory-sheet')?.scrollTop||0;armoryPulse='';if(cmd==='equipBag'&&game.s.bag[Number(arg)])armoryPulse=game.s.bag[Number(arg)].slot;else if(['upgrade','reforge'].includes(cmd))armoryPulse=arg;const feedback=['equipBag','takeLoot','collectLoot','upgrade','reforge'].includes(cmd),beforeStats=feedback?game.statSnapshot():null,beforeCode=feedback?game.export():null;game[cmd](numeric.includes(cmd)?Number(arg):arg);render();if(feedback&&beforeCode!==game.export())gearFeedback(beforeStats);save();if(['workshop','bag','equipment','quests','jobs','story'].includes(panel)&&game.s.scene==='camp'){showPanel(panel);const sheet=$('panel').querySelector('.armory-sheet');if(sheet){sheet.scrollTop=armoryScroll;const button=sheet.querySelector('[data-cmd="'+cmd+'"][data-arg="'+arg+'"]');button?.focus({preventScroll:true});}}else{closePanel()}return}
const type=target.dataset.ui;armoryPulse='';if(type?.startsWith('gear-slot-')){gearSelection={slot:type.slice(10),index:null};showPanel('equipment');return;}if(type?.startsWith('gear-bag-')){gearSelection={slot:'weapon',index:Number(type.slice(9))};showPanel('equipment');return;}if(type==='close'){closePanel();return}if(type==='confirm-restart'){game=game.newJourney();render();save();closePanel();return}if(type==='copy'){const code=$('code');code.select();if(navigator.clipboard?.writeText)navigator.clipboard.writeText(code.value).then(()=>{$('code-status').textContent='복사했습니다.'}).catch(()=>{$('code-status').textContent='전체 선택됨 · 복사 메뉴로 보관하세요.'});else $('code-status').textContent='전체 선택됨 · 복사 메뉴로 보관하세요.';return}if(type==='download'){const blob=new Blob([game.export()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='black-forest-'+new Date().toISOString().slice(0,10)+'.bfsave';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('code-status').textContent='저장 파일을 내려받았습니다. 파일 불러오기로 복원할 수 있습니다.';return}if(type?.startsWith('page-')){const [,key,direction]=type.split('-');views[key].page+=direction==='next'?1:-1;key==='jobs'?drawJobs():drawCollection();$('panel').scrollTop=0;return}if(type==='load'){try{const loaded=Game.load($('code').value);game=loaded;render();save();closePanel()}catch(e){$('code-status').textContent='불러오기 실패. 올바른 저장 코드를 넣어 주세요. 현재 진행은 유지됩니다.';$('code-status').className='error'}return}if(['workshop','bag','equipment','quests','jobs','story'].includes(type)&&game.s.scene!=='camp')return;if(type)showPanel(type)
});
root.addEventListener('submit',ev=>{if(ev.target.id!=='bf-command-form')return;ev.preventDefault();const text=$('command').value.trim(),s=game.s;let selector='';const n=text.match(/^(?:선택\s*)?([1-4])(?:번|번 선택| 선택)?$/);if(n){selector=`[data-cmd="${s.scene==='map'?'choose':s.scene==='event'?'event':s.scene==='dialogue'?'dialogue':s.scene==='bond'?'bondChoice':'none'}"][data-arg="${Number(n[1])-1}"]`}else{const aliases={'공격':'attack','공격한다':'attack','스킬':'skill','방어':'defend','물약':'potion','회복':'potion','도주':'flee'};if(aliases[text])selector=`[data-cmd="act"][data-arg="${aliases[text]}"]`;else if(text==='휴식')selector='[data-cmd="rest"]';else if(text==='귀환'||text==='캠프로')selector='[data-cmd="retreat"]';else if(text==='계속')selector=s.scene==='map'?'[data-cmd="choose"][data-arg="0"]':'[data-cmd="nextEncounter"]'}const target=selector?root.querySelector('#bf-play '+selector):null;if(target&&!target.disabled)target.click();else $('command-status').textContent='지금 실행할 수 없는 명령입니다. 화면의 선택지 또는 지원 명령을 입력하세요.';});render();if(warning)$('save-status').textContent=warning;else if(game.s.job)save();
// Optional page tools share the visible buttons and never bypass prerequisites.
if(document.modelContext?.registerTool){const life=new AbortController();const status=()=>({scene:game.s.scene,job:JOBS[game.s.job]?.name||null,hp:game.s.hp,mp:game.s.mp,location:AREAS[game.s.area].name,actions:[...root.querySelectorAll('[data-cmd]')].filter(b=>!b.disabled&&b.getClientRects().length).map(b=>({id:b.dataset.cmd+':'+b.dataset.arg,label:b.textContent.trim()}))});try{
 Promise.resolve(document.modelContext.registerTool({name:'read_rpg_status',title:'모험 상태 확인',description:'Read the current RPG status and available visible actions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>status()},{signal:life.signal})).catch(()=>{});
 Promise.resolve(document.modelContext.registerTool({name:'choose_rpg_action',title:'모험 행동 선택',description:'Execute one currently visible available game action. This advances or changes the local game.',inputSchema:{type:'object',properties:{actionId:{type:'string'}},required:['actionId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.actionId!=='string'||Object.keys(input).some(k=>k!=='actionId'))throw Error('Invalid action input');const button=[...root.querySelectorAll('[data-cmd]')].find(b=>!b.disabled&&b.getClientRects().length&&b.dataset.cmd+':'+b.dataset.arg===input.actionId);if(!button)throw Error('Action unavailable');button.click();return status()}},{signal:life.signal})).catch(()=>{});
 }catch(e){}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
})();

